### ISSUE TITLE
Using WebDAV can't upload file correctly

### ISSUE THREAD

**Issue by TsingJyujing** [chrislusf/seaweedfs#1114]
**Describe the bug**
Upload images by WebDAV (Using Mac Finder to mount)

**System Setup**
```yaml
version: '3'

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
    command: "master -mdir /data"
    volumes:
      - "./data/meta/:/data/"
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 9301:9301
    command: 'volume -max=30 -mserver="master:9333" -port=9301'
    volumes:
      - "./data/volume/:/data/"
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 9401:9401
    command: 'filer -master="master:9333" -port=9401 -dirListLimit 1000000'
    volumes:
      - "./data/filer/:/data/"
      - "./data/filer.toml:/etc/seaweedfs/filer.toml"
    depends_on:
      - volume
  webdav:
    image: chrislusf/seaweedfs
    ports:
      - 9501:9501
    command: 'webdav -filer="filer:9401" -port=9501'
    depends_on:
      - filer
```

And filer.toml is:

```toml
[leveldb2]
enabled = true
dir = "/data"
```

**Expected behavior**
I'm using drag to copy some image to weedfs.
Every image been uplaoded but size is not correct (around 8.2kb only) and I can't open the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/7792749/68568524-26790d00-049f-11ea-8a01-ddde6e04f1b7.png)

**Additional context**
My develop machine is Mac but running in docker, so, bascially it's linux x64.

After I checked the response of filer, I think it may caused by file splited into 8k chucks but do not processed it well while it return.

This is my log
```
curl "http://127.0.0.1:9401/Saber/?pretty=y"  -H "Accept: application/json"                                  
{
  "Path": "/Saber",
  "Entries": [
    {
      "FullPath": "/Saber/46533.jpg",
      "Mtime": "2019-11-11T07:12:33Z",
      "Crtime": "2019-11-11T07:12:32Z",
      "Mode": 438,
      "Uid": 0,
      "Gid": 0,
      "Mime": "",
      "Replication": "000",
      "Collection": "",
      "TtlSec": 0,
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "chunks": [
        {
          "file_id": "1,3d131f712d",
          "size": 8192,
          "mtime": 1573456353173267066,
          "e_tag": "911b4c47",
          "fid": {
            "volume_id": 1,
            "file_key": 61,
            "cookie": 320827693
          }
        },
        {
          "file_id": "5,3e0590e3b4",
          "size": 2402,
          "mtime": 1573456353177545523,
          "e_tag": "2675633e",
          "fid": {
            "volume_id": 5,
            "file_key": 62,
            "cookie": 93381556
          }
        }
      ]
    },
    {
      "FullPath": "/Saber/673234.jpg",
      "Mtime": "2019-11-11T07:12:33Z",
      "Crtime": "2019-11-11T07:12:33Z",
      "Mode": 438,
      "Uid": 0,
      "Gid": 0,
      "Mime": "",
      "Replication": "000",
      "Collection": "",
      "TtlSec": 0,
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "chunks": [
        {
          "file_id": "5,c0913906e9",
          "size": 8192,
          "mtime": 1573456353884347644,
          "e_tag": "3b2d0323",
          "fid": {
            "volume_id": 5,
            "file_key": 192,
            "cookie": 2436433641
          }
        },
        {
          "file_id": "2,c14889084b",
          "size": 4774,
          "mtime": 1573456353890302234,
          "e_tag": "bd6dd06a",
          "fid": {
            "volume_id": 2,
            "file_key": 193,
            "cookie": 1216940107
          }
        }
      ]
    },
    {
      "FullPath": "/Saber/677688.png",
      "Mtime": "2019-11-11T07:12:36Z",
      "Crtime": "2019-11-11T07:12:33Z",
      "Mode": 438,
      "Uid": 0,
      "Gid": 0,
      "Mime": "",
      "Replication": "000",
      "Collection": "",
      "TtlSec": 0,
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "chunks": [
        {
          "file_id": "4,0259ffd7c726",
          "size": 8192,
          "mtime": 1573456356439480541,
          "e_tag": "c172a19e",
          "fid": {
            "volume_id": 4,
            "file_key": 601,
            "cookie": 4292331302
          }
        },
        {
          "file_id": "7,025a73f3d4ed",
          "size": 6760,
          "mtime": 1573456356445487040,
          "e_tag": "ee7ed1f5",
          "fid": {
            "volume_id": 7,
            "file_key": 602,
            "cookie": 1945359597
          }
        }
      ]
    },
    {
      "FullPath": "/Saber/808397.png",
      "Mtime": "2019-11-11T07:12:38Z",
      "Crtime": "2019-11-11T07:12:36Z",
      "Mode": 438,
      "Uid": 0,
      "Gid": 0,
      "Mime": "",
      "Replication": "000",
      "Collection": "",
      "TtlSec": 0,
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "chunks": [
        {
          "file_id": "6,0392621034f8",
          "size": 8192,
          "mtime": 1573456358323309884,
          "e_tag": "63c4ba49",
          "fid": {
            "volume_id": 6,
            "file_key": 914,
            "cookie": 1645229304
          }
        },
        {
          "file_id": "3,0393a86aa649",
          "size": 1848,
          "mtime": 1573456358328696839,
          "e_tag": "428f9adc",
          "fid": {
            "volume_id": 3,
            "file_key": 915,
            "cookie": 2825561673
          }
        }
      ]
    }
  ],
  "Limit": 100,
  "LastFileName": "808397.png",
  "ShouldDisplayLoadMore": false
}%                        
```

And I checked the WebDAV can read the file uploaded to filer by filer API normally, just can't upload.
