### ISSUE TITLE
Feature: add an upload file size limit to protect volume servers

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/seaweedfs#1127]
If the upload file size limit is configured, any file larger than the limit would not be uploaded.

Default to no limit.

**Comment by ingardm** [comment]
@chrislusf What happens if you upload a file that is bigger than available space on the volume?

**Comment by chrislusf** [comment]
`-fileSizeLimitMB` has been added to volume server, default to 256MB to avoid out of memory if abused by some clients.

**Comment by chrislusf** [comment]
> @chrislusf What happens if you upload a file that is bigger than available space on the volume?

Fail. Any other possible way?

**Comment by gilillo32** [comment]
> `-fileSizeLimitMB` has been added to volume server, default to 256MB to avoid out of memory if abused by some clients.


Hello! How should this feature be used? I'm trying to set the upload limit to 5GB in a dockerized volume server, but is not working and I don't know if I'm missing something.
  ```
seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs_volume
    ports:
      - "8080:8080"
    command: 'volume -dir=/data -port=8080 -mserver=seaweedfs_master:9333 -fileSizeLimitMB=5120 -concurrentUploadLimitMB=5120 -concurrentDownloadLimitMB=5120'
    volumes:
        - ./seaweedfs/volume-data:/data
    depends_on:
      - seaweedfs-master
    restart: always
```

With this settings, when I try to upload a bigger file than the default max size (256MB) I'm getting this error:
`response method:POST URL:/submit with httpStatus:400 and JSON:{"error":"file over the limited 268435456 bytes"}`
