### ISSUE TITLE
问下为什么在docker中volume开放了端口依旧无法访问0.0.0.0:8080，但是其他9333和8888是可以访问的，这是为什么呢？

### ISSUE THREAD

**Issue by GeorgeWang1994** [chrislusf/seaweedfs#1147]
下面是我写的dockerfile，问题如题目：

```
services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 9333:9333
    - 19333:19333
    command: 'master -ip.bind="0.0.0.0"'
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 8080:8080
    - 18080:18080
    command: 'volume -max=15 -mserver="master:9333" -ip.bind="0.0.0.0" -port=8080'
    depends_on:
    - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 8888:8888
    - 18888:18888
    command: 'filer -master="master:9333" -ip="0.0.0.0"'
    tty: true
    stdin_open: true
    depends_on:
    - master
    - volume
```

**Comment by chrislusf** [comment]
Try other port. 8080 may be in use.

**Comment by GeorgeWang1994** [comment]
已经试过了，还是一样。

**Comment by chrislusf** [comment]
works for me

**Comment by GeorgeWang1994** [comment]
我说的是网页不能打开，请问你配置的是什么端口呢？

**Comment by GeorgeWang1994** [comment]
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 9333:9333
    - 19333:19333
    command: 'master -ip.bind="0.0.0.0" -ip="0.0.0.0"'
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 9999:9999
    - 18080:18080
    command: 'volume -max=15 -mserver="master:9333" -ip.bind="0.0.0.0" -ip="0.0.0.0" -port=9999 -port.public=9999'
    depends_on:
    - master
  filer:
      image: chrislusf/seaweedfs # use a remote image
      ports:
        - 8888:8888
        - 18888:18888
      command: 'filer -master="master:9333" -ip="0.0.0.0"'
      tty: true
      stdin_open: true
      depends_on:
        - master
        - volume
```


![image](https://user-images.githubusercontent.com/29206315/70403299-6b2d9f00-1a71-11ea-9b69-44a537a53094.png)


![image](https://user-images.githubusercontent.com/29206315/70403277-581acf00-1a71-11ea-9e00-45e3707bb506.png)
