### ISSUE TITLE
Volume server exited with code 137 while uploading

### ISSUE THREAD

**Issue by TsingJyujing** [chrislusf/seaweedfs#1183]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
Volume server exited with code 137 while uploading

**System Setup**
- Using latest version docker on Mac
- Yaml file:
```yaml
version: '3'

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
    command: "master -mdir /data -ip=master"
    volumes:
      - "./data/meta/:/data/"
    healthcheck:
      test: "curl http://localhost:9333/ -f || exit 1"
      interval: 10s
      timeout: 5s
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 9301:9301
    command: 'volume -max=30 -mserver="master:9333" -port=9301'
    volumes:
      - "./data/volume/:/data/"
    healthcheck:
      test: "curl http://localhost:9301/status -f || exit 1"
      interval: 10s
      timeout: 5s
    depends_on:
      - master
```

**Expected behavior**
Trying to upload a large file to volume and exited with code 137:
```
curl -F file=@/xx/xxxx/xxx/xxx.zip http://127.0.0.1:9301/3,53ef59248e 
curl: (55) Send failure: Broken pipe
```

and log shows:
```
master_1   | I0118 14:54:44     1 master_grpc_server.go:24] unregister disconnected volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 topology_event_handling.go:57] Removing Volume 2 from the dead volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 volume_layout.go:261] Volume 2 has 0 replica, less than required 1
master_1   | I0118 14:54:44     1 volume_layout.go:237] Volume 2 becomes unwritable
master_1   | I0118 14:54:44     1 topology_event_handling.go:57] Removing Volume 6 from the dead volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 volume_layout.go:261] Volume 6 has 0 replica, less than required 1
master_1   | I0118 14:54:44     1 volume_layout.go:237] Volume 6 becomes unwritable
master_1   | I0118 14:54:44     1 topology_event_handling.go:57] Removing Volume 4 from the dead volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 volume_layout.go:261] Volume 4 has 0 replica, less than required 1
master_1   | I0118 14:54:44     1 volume_layout.go:237] Volume 4 becomes unwritable
master_1   | I0118 14:54:44     1 topology_event_handling.go:57] Removing Volume 7 from the dead volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 volume_layout.go:261] Volume 7 has 0 replica, less than required 1
master_1   | I0118 14:54:44     1 volume_layout.go:237] Volume 7 becomes unwritable
master_1   | I0118 14:54:44     1 topology_event_handling.go:57] Removing Volume 1 from the dead volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 volume_layout.go:261] Volume 1 has 0 replica, less than required 1
master_1   | I0118 14:54:44     1 volume_layout.go:237] Volume 1 becomes unwritable
master_1   | I0118 14:54:44     1 topology_event_handling.go:57] Removing Volume 5 from the dead volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 volume_layout.go:261] Volume 5 has 0 replica, less than required 1
master_1   | I0118 14:54:44     1 volume_layout.go:237] Volume 5 becomes unwritable
master_1   | I0118 14:54:44     1 topology_event_handling.go:57] Removing Volume 3 from the dead volume server 172.25.0.4:9301
master_1   | I0118 14:54:44     1 volume_layout.go:261] Volume 3 has 0 replica, less than required 1
master_1   | I0118 14:54:44     1 volume_layout.go:237] Volume 3 becomes unwritable
master_1   | I0118 14:54:44     1 node.go:256] topo:DefaultDataCenter:DefaultRack removes 172.25.0.4:9301
nemivir_volume_1 exited with code 137
```
