### ISSUE TITLE
support private host s3 storage backend

### ISSUE THREAD

**Issue by wyxloading** [chrislusf/seaweedfs#1238]
Better to add s3 endpoint setting to support some kind of private host s3 implementation.

Read the `endpoint` setting from env is not supported by aws-go-sdk

```toml
# configurations for tiered cloud storage
# old volumes are transparently moved to cloud for cost efficiency
[storage.backend]
        [storage.backend.s3.default]
        enabled = false
        aws_access_key_id     = ""     # if empty, loads from the shared credentials file (~/.aws/credentials).
        aws_secret_access_key = ""     # if empty, loads from the shared credentials file (~/.aws/credentials).
        region = "us-east-2"
        bucket = "your_bucket_name"    # an existing bucket
        endpoint = ""
```
