### ISSUE TITLE
docker deploy volume command -dir="/xxx" not work

### ISSUE THREAD

**Issue by youngcube** [chrislusf/seaweedfs#1274]
Hi

I want to deploy weedfs with docker-compose in my ubuntu server and use mounted disk in host server so that i can keep my data.

I followed this `seaweedfs-compose.yml` without any changes and it works like a charm.

but I found two problems when i modified this compose file. 

- I tried to append command `-dir="/xxx"` and see docker logs still print `Store started on dir: /data with 0 volumes max 7`

Here's my `docker-compose` brief for this issue:
```yml
volume:
    image: chrislusf/seaweedfs:${WEEDFS_VERSION} # use a remote image
    restart: always
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -dataCenter=TestDataCenter -rack=TestRack -port=8080 -dir="/testdata"'
    container_name: weedfs_volume
    volumes:
      - type: bind
        source: /data/disk1
        target: /testdata
    depends_on:
      - master
```

- If I bind `/data` to any local folder, docker logs print `Store started on dir: /data with 0 volumes max 0`. Even if i append -max=7.

Here's `docker-compose` brief for this issue:
```yml
volume:
    image: chrislusf/seaweedfs:${WEEDFS_VERSION} # use a remote image
    restart: always
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -dataCenter=TestDataCenter -rack=TestRack -port=8080 -max=7'
    container_name: weedfs_volume
    volumes:
      - type: bind
        source: /data/disk1
        target: /data
    depends_on:
      - master
```
But when i visit `{volume}:8080/ui/index.html`, I can know that `/data` is using the right place according to `Disk Stats->Free/Usage`

------
Both two conditions I can not upload any file. master api gave me this error: 
`"error": "rpc error: code = Unknown desc = No free volumes left!"` 

Version: 1.74

Please tell me if I use it wrong or there are some bugs in weedfs.
Thanks

**Comment by chrislusf** [comment]
`-dir` and `-max` are already set in entrypoint.sh on the image.

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/blob/master/docker/entrypoint.sh

**Comment by youngcube** [comment]
Thanks for your quick reply!

Here's another question. Now I bind local volume to `/data/disk1`

```yml
master:
    image: chrislusf/seaweedfs:${WEEDFS_VERSION} # use a remote image
    restart: always
    ports:
      - 9333:9333
      - 19333:19333
    command: 'master -ip=master'
    container_name: weedfs_master
    volumes:
      - /data/master:/data

volume:
    image: chrislusf/seaweedfs:${WEEDFS_VERSION} # use a remote image
    restart: always
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -dataCenter=TestDataCenter -rack=TestRack -port=8080'
    container_name: weedfs_volume
    volumes:
      - type: bind
        source: /data/disk1
        target: /data
    depends_on:
      - master
```

When upload a file to weedfs. 
- `/data/disk1` has files like `1.idx` `1.dat` ...
- `/data/master` has files `conf`,`log`,`snapshot(folder)`

It looks like the file was uploaded successfully.
- `http://filter:8888/` can see these files.
- `webdav` can mount and can download files

However, when I close all docker (`master`, ` volume`, `filer`) and reopen these dockers again, my files are not visible in `filer` and `webdav`

-  `/data/disk1`, `/data/master`  has all data and they are not been modified or deleted during my restart docker action.
- `/data/disk1`, `/data/master`  all files are all the same
- `http://volume:8080.ui/index.html` -> `Disk Stats` are almost the same `Usage`

How can I deploy weedfs with docker and restart docker without losing all files(or it's just not visible from `filer` or `webdav`)? Thanks!
