### ISSUE TITLE
After upgrading with docker,all my file are 404

### ISSUE THREAD

**Issue by yhan219** [chrislusf/seaweedfs#1362]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
Before that, I used version 1.0. Today, I updated the version with docker, but my file access is 404.
my `docker-compose.yml`
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs:1.81 #use a remote image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
    volumes:
      - /mnt/file/data:/data
  volume:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    ports:
      - 9222:8080
      - 19222:18080
    command: 'volume -mserver="master:9333" -port=8080 -publicUrl=/file'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    ports:
      - 9255:8888
      - 19255:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
    volumes:
      - /mnt/file/filerdb:/data/filerdb
  cronjob:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    command: 'cronjob'
    environment:
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: master:9333 # Default: localhost:9333
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
```

my file url:
`http://localhost:9222/9334,3c92e4dede583a`
and master log:
```
I0618 17:46:29     1 common.go:51] response method:POST URL:/dir/lookup with httpStatus:404 and JSON:{"volumeId":"9334","error":"volume id 9334 not found"}
```
But the file exists
```
ls /mnt/file/data/ | grep 9334
work_9334.dat
work_9334.idx
```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
the volume server did not mount the directory.

**Comment by yhan219** [comment]
Sorry, I still don't know what to do.
After I enter the container, Files exist in the `/data` directory,too.
```
docker exec -it file_master_1 sh
/ # ls /data/ | grep 9334
work_9334.dat
work_9334.idx
```

Can you help me change the code? Thank you very much.

**Comment by yhan219** [comment]
i change the volume
```
volume:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    ports:
      - 9222:8080
      - 19222:18080
    command: 'volume -mserver="master:9333" -port=8080 -publicUrl=/file'
    depends_on:
      - master
    volumes:
      - /mnt/file/data:/data
```
is is ok,thank you!
