### ISSUE TITLE
harbor registry with seaweed-s3 has error

### ISSUE THREAD

**Issue by gitbeyond** [chrislusf/seaweedfs#1407]
**Describe the bug**
# issue desc
## harbor registry use s3 storage
```yaml
storage:
      s3:
        region: us-west-1 
        bucket: harbor
        accesskey: harborAccessKey9k2
        secretkey: harborSecretKey9Mn
        regionendpoint: http://10.111.32.55:8333
        #keyid: harbor
        secure: false
        v4auth: false
        chunksize: 5242880
        rootdirectory: /
```

## `seaweed-s3 -config` file 
```json
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "adminAccessKey73h",
          "secretKey": "adminSecretKey98n"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "Write"
      ]
    },
    {
      "name": "harbor",
      "credentials": [
        {
          "accessKey": "harborAccessKey9k2",
          "secretKey": "harborSecretKey9Mn"
        }
      ],
      "actions": [
        "Read:harbor",
        "Write:harbor"
      ]
    }
  ]
}
```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```bash
# weed-volume
/data/apps/opt/seaweed/weed volume -dataCenter dc1 -rack rack1 -dir /data/apps/data/seaweed-volume -ip 10.111.32.55 -port 9222 -ip.bind 10.111.32.55 -max 20 -mserver 10.111.32.55:9333,10.111.32.58:9333,10.111.32.61:9333 -publicUrl 10.111.32.55:9222
# weed-master
/data/apps/opt/seaweed/weed master -ip=10.111.32.55 -port=9333 -mdir=/data/apps/data/seaweed-master -peers=10.111.32.55:9333,10.111.32.58:9333,10.111.32.61:9333 -defaultReplication=002 -metrics.address=10.111.32.178/pushgateway/
# weed-filer
/data/apps/opt/seaweed/weed -logdir /data/apps/log/seaweed-filer filer -master=10.111.32.55:9333,10.111.32.58:9333,10.111.32.61:9333 -ip=10.111.32.55 -port=8888 -defaultReplicaPlacement=002 -dataCenter=dc1

# weed-s3
/data/apps/opt/seaweed/weed -logdir /data/apps/log/seaweed-s3 s3 -filer=10.111.32.55:8888 -port=8333 -config=s3-config.json


```
- OS version: centos-7.4
- output of `weed version`: seaweed-1.74_large_disk
- if using filer, show the content of `filer.toml`
```toml
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
	"important_bucket",
	"should_always_fsync",
]

####################################################
# The following are filer store options
####################################################

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "/data/apps/data/seaweed-filer"					# directory to store level db files

[mysql]  # or tidb
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT         COMMENT 'first 64 bits of MD5 hash value of directory field',
#   name        VARCHAR(1000)  COMMENT 'directory or file name',
#   directory   TEXT           COMMENT 'full path to parent directory',
#   meta        LONGBLOB,
#   PRIMARY KEY (dirhash, name)
# ) DEFAULT CHARSET=utf8;

enabled = false
hostname = "localhost"
port = 3306
username = "root"
password = ""
database = ""              # create or use an existing database
connection_max_idle = 2
connection_max_open = 100
interpolateParams = false

[postgres] # or cockroachdb
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT,
#   name        VARCHAR(65535),
#   directory   VARCHAR(65535),
#   meta        bytea,
#   PRIMARY KEY (dirhash, name)
# );
enabled = false
hostname = "localhost"
port = 5432
username = "postgres"
password = ""
database = ""              # create or use an existing database
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100

[cassandra]
# CREATE TABLE filemeta (
#    directory varchar,
#    name varchar,
#    meta blob,
#    PRIMARY KEY (directory, name)
# ) WITH CLUSTERING ORDER BY (name ASC);
enabled = false
keyspace="seaweedfs"
hosts=[
	"localhost:9042",
]

[redis2]
enabled = false
address  = "localhost:6379"
password = ""
database = 0

[redis_cluster2]
enabled = false
addresses = [
    "localhost:30001",
    "localhost:30002",
    "localhost:30003",
    "localhost:30004",
    "localhost:30005",
    "localhost:30006",
]
password = ""
# allows reads from slave servers or the master, but all writes still go to the master
readOnly = true
# automatically use the closest Redis server for reads
routeByLatency = true

[etcd]
enabled = false
servers = "localhost:2379"
timeout = "3s"
```
* harbor version: 
```bash
# cat Chart.yaml
apiVersion: v1
appVersion: 2.0.1
description: An open source trusted cloud native registry that stores, signs, and
  scans content
engine: gotpl
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/harbor/master/docs/img/harbor_logo.png
keywords:
- docker
- registry
- harbor
maintainers:
- email: yinw@vmware.com
  name: Wenkai Yin
- email: hweiwei@vmware.com
  name: Weiwei He
- email: dengq@vmware.com
  name: Qian Deng
name: harbor
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
version: 1.4.1

```
* registry image verion: goharbor/registry-photon:v2.0.1

# registry error log

```bash
time="2020-07-30T05:47:48.463316612Z" level=debug msg="s3aws.Writer("/docker/registry/v2/repositories/library/busybox/_uploads/a9e73de9-b53a-47ca-9592-37d7953900ab/data", true)" auth.user.name="harbor_registry_user" go.version=go1.13.8 http.request.host=test-harbor.myregistry.com http.request.id=b31b1d91-e5f1-4e86-8ce6-7bd4005ae5de http.request.method=PATCH http.request.remoteaddr=10.111.32.182 http.request.uri="/v2/library/busybox/blobs/uploads/a9e73de9-b53a-47ca-9592-37d7953900ab?_state=_lbjABgU35zh_bGiC9qMVrCybH-QvbNdPc9bgWBQQ6h7Ik5hbWUiOiJsaWJyYXJ5L2J1c3lib3giLCJVVUlEIjoiYTllNzNkZTktYjUzYS00N2NhLTk1OTItMzdkNzk1MzkwMGFiIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIwLTA3LTMwVDA1OjQ3OjQ4LjAwNDU4Njk1NloifQ%3D%3D" http.request.useragent="docker/18.02.0-ce go/go1.9.3 git-commit/fc4de44 kernel/3.10.0-1127.13.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.02.0-ce \(linux\))" trace.duration=1.403371ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Writer" trace.id=f373ab3f-b5ad-4599-8c13-f00e83eae0df trace.line=142 vars.name="library/busybox" vars.uuid=a9e73de9-b53a-47ca-9592-37d7953900ab 
time="2020-07-30T05:47:48.463374001Z" level=error msg="error resolving upload: s3aws: Path not found: /docker/registry/v2/repositories/library/busybox/_uploads/a9e73de9-b53a-47ca-9592-37d7953900ab/data" auth.user.name="harbor_registry_user" go.version=go1.13.8 http.request.host=test-harbor.myregistry.com http.request.id=b31b1d91-e5f1-4e86-8ce6-7bd4005ae5de http.request.method=PATCH http.request.remoteaddr=10.111.32.182 http.request.uri="/v2/library/busybox/blobs/uploads/a9e73de9-b53a-47ca-9592-37d7953900ab?_state=_lbjABgU35zh_bGiC9qMVrCybH-QvbNdPc9bgWBQQ6h7Ik5hbWUiOiJsaWJyYXJ5L2J1c3lib3giLCJVVUlEIjoiYTllNzNkZTktYjUzYS00N2NhLTk1OTItMzdkNzk1MzkwMGFiIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIwLTA3LTMwVDA1OjQ3OjQ4LjAwNDU4Njk1NloifQ%3D%3D" http.request.useragent="docker/18.02.0-ce go/go1.9.3 git-commit/fc4de44 kernel/3.10.0-1127.13.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.02.0-ce \(linux\))" vars.name="library/busybox" vars.uuid=a9e73de9-b53a-47ca-9592-37d7953900ab 
10.20.89.167 - - [30/Jul/2020:05:47:48 +0000] "PATCH /v2/library/busybox/blobs/uploads/a9e73de9-b53a-47ca-9592-37d7953900ab?_state=_lbjABgU35zh_bGiC9qMVrCybH-QvbNdPc9bgWBQQ6h7Ik5hbWUiOiJsaWJyYXJ5L2J1c3lib3giLCJVVUlEIjoiYTllNzNkZTktYjUzYS00N2NhLTk1OTItMzdkNzk1MzkwMGFiIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIwLTA3LTMwVDA1OjQ3OjQ4LjAwNDU4Njk1NloifQ%3D%3D HTTP/1.1" 500 199 "" "docker/18.02.0-ce go/go1.9.3 git-commit/fc4de44 kernel/3.10.0-1127.13.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.02.0-ce \\(linux\\))"
time="2020-07-30T05:47:48.463474383Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: Path not found: /docker/registry/v2/repositories/library/busybox/_uploads/a9e73de9-b53a-47ca-9592-37d7953900ab/data" err.message="unknown error" go.version=go1.13.8 http.request.host=test-harbor.myregistry.com http.request.id=b31b1d91-e5f1-4e86-8ce6-7bd4005ae5de http.request.method=PATCH http.request.remoteaddr=10.111.32.182 http.request.uri="/v2/library/busybox/blobs/uploads/a9e73de9-b53a-47ca-9592-37d7953900ab?_state=_lbjABgU35zh_bGiC9qMVrCybH-QvbNdPc9bgWBQQ6h7Ik5hbWUiOiJsaWJyYXJ5L2J1c3lib3giLCJVVUlEIjoiYTllNzNkZTktYjUzYS00N2NhLTk1OTItMzdkNzk1MzkwMGFiIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDIwLTA3LTMwVDA1OjQ3OjQ4LjAwNDU4Njk1NloifQ%3D%3D" http.request.useragent="docker/18.02.0-ce go/go1.9.3 git-commit/fc4de44 kernel/3.10.0-1127.13.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.02.0-ce \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=133.72843ms http.response.status=500 http.response.written=199 vars.name="library/busybox" vars.uuid=a9e73de9-b53a-47ca-9592-37d7953900ab 
```

## docker push image info
```bash
[root@docker-182 buckets]# docker push test-harbor.myregistry.com/library/busybox
The push refers to repository [test-harbor.myregistry.com/library/busybox]
6a749002dd6a: Pushing [==================================================>]  1.338MB
received unexpected HTTP status: 500 Internal Server Error

```
On seaweedfs, I can only see some directories, but not the actual files. The path reported by registry does not exist.

**Comment by chrislusf** [comment]
Can you try to configure v4auth:true for harbor?

**Comment by chrislusf** [comment]
need logs to see what was wrong. 

no response. can not proceed.

**Comment by gitbeyond** [comment]
Thank you for your reply. I'm sorry I didn't reply in time.

I upgraded seaweed to version 1.90 and tried:
1. set s3.v4auth: true
2. weed s3 run without config : `/data/apps/opt/seaweed/weed -logdir /data/apps/log/seaweed-s3 s3 -filer=10.111.32.55:8888 -port=8333`


After this operation, the error still remains.

**Comment by chrislusf** [comment]
I do not know how to setup harbor to reproduce this. Seems complicated.

**Comment by gitbeyond** [comment]
Have you ever successfully deployed harbor with weed S3?

**Comment by gitbeyond** [comment]
The deployment of harbor on k8s requires PgSQL, redis, and then S3 storage. You can also use weed mount to store images. Now I use the way of weed mount. If S3 still doesn't work, I'm going to try seaweedfs CSI driver.It's much better than mounting it myself.

**Comment by chrislusf** [comment]
I do not know how to setup harbor to reproduce this. Maybe create some docker image that I can use directly?

**Comment by gitbeyond** [comment]
```yaml
storage:
    s3:
        region: us-west-1 
        bucket: harbor
        accesskey: harborAccessKey9k2
        secretkey: harborSecretKey9Mn
        regionendpoint: http://10.111.32.55:8333
        #keyid: harbor
        secure: false
        v4auth: false
        chunksize: 5242880
        rootdirectory: /
```

I use this configuration. After starting harbor, the docker pull image will report an error.

Do you have a harbor environment? Is he normal? What is his version?
