### ISSUE TITLE
Memory used very large

### ISSUE THREAD

**Issue by joveth** [chrislusf/seaweedfs#1483]
**Describe the bug**
I'm using docker-compose to deploy seaweedfs.
When use docker stats ,it showed the seaweedfs app use a very large memory.
I don't know why?

**System Setup**
My  yml file is:

```
 filemaster:
    image: chrislusf/seaweedfs:2.00
    privileged: true
    ports:
      - "9333:9333"
      - "8777:8777"
    volumes:
      - "$PWD/filedata/mdata:/data"
    command: server  -master.port=9333   -volume.port=8777  -volume.max=200 -dir=/data
    network_mode: "bridge"


```

**Expected behavior**
Low memory used.

**Screenshots**
![6304C9BE-C2CE-4fc4-8A34-7E7E8A55F842](https://user-images.githubusercontent.com/6395299/93996306-ab71ca00-fdc4-11ea-9f06-fef59b726683.png)

**Additional context**
no
