### ISSUE TITLE
S3 with VirtualHost style paths does not work

### ISSUE THREAD

**Issue by SharkyRawr** [chrislusf/seaweedfs#1510]
From what I gathered the S3 gateway should be able to deal with `bucketname.hostname.tld/somefile` style paths - but it doesn't want to work in my environment.

It does not parse the subdomain from the Host header as a bucket.

https://s3.catgirl.biz/test/foxavatar.jpg - works  
https://test.s3.catgirl.biz/foxavatar.jpg - does not work  
https://test.s3.catgirl.biz/test/foxavatar.jpg - does work but is an undesired side-effect

I have confirmed with tcpdump that the Host header is being passed from nginx to the s3 server.

It does work this way with minio but I'm hoping to use seaweedfs in the long run.

docker-compose:
```
 s3:
    image: chrislusf/seaweedfs:dev # use a remote image
    restart: unless-stopped
    network_mode: host
    command: 's3 -filer="10.88.1.1:7777" -config=/config.json -domainName="s3.catgirl.biz" -metricsPort=8334'
    volumes:
      - ./s3.json:/config.json
    depends_on:
      - master
      - volume
      - filer
```

```
     Container            Repository         Tag       Image Id      Size  
---------------------------------------------------------------------------
seaweedfs_cronjob_1   chrislusf/seaweedfs   latest   a01a236dc701   79.4 MB
seaweedfs_filer_1     chrislusf/seaweedfs   dev      cd7f9bbae7d9   74.6 MB
seaweedfs_master_1    chrislusf/seaweedfs   dev      cd7f9bbae7d9   74.6 MB
seaweedfs_s3_1        chrislusf/seaweedfs   dev      cd7f9bbae7d9   74.6 MB
seaweedfs_volume_1    chrislusf/seaweedfs   dev      cd7f9bbae7d9   74.6 MB
```
```
# docker-compose exec master weed version
version 30GB 2.03  linux amd64
```

nginx:
```
[...]
server_name                             s3.catgirl.biz *.s3.catgirl.biz;
[...]
       location / {
                proxy_pass http://10.0.0.1:8333;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_buffering off;
                client_max_body_size 0;

                proxy_http_version 1.1;
                proxy_set_header Connection "";
                chunked_transfer_encoding off;

                proxy_connect_timeout 1800;
                proxy_send_timeout 1800;
                proxy_read_timeout 1800;
                send_timeout 1800;

        }
```

As far as I could gather this should be enough to make it work(?) Any insight would be greatly appreciated!
