### ISSUE TITLE
Streaming MP4 from s3 endpoint (no Auth) breaks starting on 1.85

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [chrislusf/seaweedfs#1527]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

**Describe the bug**
connecting directly with Network Stream in VLC to a file/video location on a HTTP connection to S3 endpoint
works  on seaweedfs  <= 1.84
breaks on seaweedfs >= 1.85

**System Setup**
```
  seaweedfs-master:
    image: chrislusf/seaweedfs:2.02
    restart: always
    command: "-logdir=/logs -v=1 master -ip=seaweedfs-master-localnode.tls.ai -mdir=/data"
    networks:
      bridge:
        aliases:
         - seaweedfs-master-localnode.tls.ai
    volumes:
      - /ssd/seaweed-master:/data
      - /storage/logs/seaweedfs/master:/logs
    logging:
      options:
        max-size: 1g


  seaweedfs-volume:
    image: chrislusf/seaweedfs:2.02
    restart: always
    command: '-logdir=/logs -v=1 volume -max=10000 -ip=seaweedfs-volume-localnode.tls.ai -mserver=seaweedfs-master-localnode.tls.ai:9333 -port=8080 -dir=/data -compactionMBps=40'
    networks:
      bridge:
        aliases:
         - seaweedfs-volume-localnode.tls.ai
    volumes:
      - /storage/seaweed:/data
      - /storage/logs/seaweedfs/volume:/logs
    logging:
      options:
        max-size: 1g
    depends_on:
      - seaweedfs-master


  seaweedfs-filer:
    image: chrislusf/seaweedfs:2.02
    restart: always
    command: '-logdir=/logs -v=1 filer -master=seaweedfs-master-localnode.tls.ai:9333 -ip=seaweedfs-filer-localnode.tls.ai'
    networks:
      bridge:
        aliases:
         - seaweedfs-filer-localnode.tls.ai
    ports:
       - "8888:8888"
    environment:
      - WEED_FILER_OPTIONS_RECURSIVE_DELETE=true
      - WEED_LEVELDB2_ENABLED=true
      - WEED_LEVELDB2_DIR=/data/filerldb2
      - WEED_FILER_OPTIONS_BUCKETS_FOLDER=/buckets
    volumes:
      - /ssd/seaweed-filer/filerldb2:/data/filerldb2
      - /storage/logs/seaweedfs/filer:/logs
    logging:
      options:
        max-size: 1g
    depends_on:
      - seaweedfs-master


  seaweedfs-s3:
    image: chrislusf/seaweedfs:2.02
    restart: always
    command: '-logdir=/logs -v=1 s3 -filer=seaweedfs-filer-localnode.tls.ai:8888 -port=8333'
    networks:
      bridge:
        aliases:
         - seaweedfs-s3-localnode.tls.ai
         - seaweedfs-s3
    ports:
       - "8333:8333"
    volumes:
      - /storage/logs/seaweedfs/s3:/logs
    logging:
      options:
        max-size: 1g
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
      - seaweedfs-filer
```

- OS version : ubuntu 20.04 (running dockers)

**Expected behavior**
Streaming of the video file should continue to work with filer 1.85+

**VLC debug log(ERROR, all pods 2.02)**
http debug: incoming response: HTTP/1.1 200 OK Accept-Ranges: bytes Content-Disposition: inline; filename="net_2020-10-12_17-18-55.mp4" Content-Length: 1899467 Content-Range: bytes 48-1899514/1899515 Content-Type: application/octet-stream Date: Mon, 12 Oct 2020 17:49:44 GMT Etag: "ced5d0c6bc93edf05bc372e7c5da1185" Last-Modified: Mon, 12 Oct 2020 17:19:47 GMT Server: SeaweedFS Filer 30GB 2.02 
prefetch error: cannot seek (to offset 48)
mp4 warning: track[0x1] will be disabled (eof?): Failed to read 210098 bytes sample at 48

**VLC debug log(WORKING, all pods 2.02 except filer in 1.84)**
http debug: incoming response: HTTP/1.1 206 Partial Content Accept-Ranges: bytes Content-Disposition: inline; filename="net_2020-10-12_17-18-55.mp4" Content-Length: 1899467 Content-Range: bytes 48-1899514/1899515 Content-Type: application/octet-stream Date: Mon, 12 Oct 2020 17:54:26 GMT Etag: "ced5d0c6bc93edf05bc372e7c5da1185" Last-Modified: Mon, 12 Oct 2020 17:19:47 GMT Server: SeaweedFS S3 30GB 2.02 
main debug: Buffering 0%
