### ISSUE TITLE
Max number of volumes on volume server are not recalculated on diskspace change

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#1594]
**Describe the bug**
Have a HDD that is 8TB big. Use 200GB volumes. Have around 2.5TB free space on that disk.
On volume start, the volume will report that the max number of volumes is 13. 
Free up the disk so you have more than 3TB of free space.

Volume/Master will still repot that only 13 volumes are available, while the "Disk Stats" shows that there is free space.
Write to the seaweed fails because there is not enough volumes even though there is enough space.

**System Setup**
<details>
<summary>Docker compose</summary>

```
version: '2'
services:
  seaweed-master:
    container_name: seaweed-master
    image: chrislusf/seaweedfs:2.07_large_disk # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
    volumes:
      - /snapraid/storage_c1/docker/seaweedfs/config/master.toml:/etc/seaweedfs/master.toml
      - /snapraid/storage_c1/docker/seaweedfs/entrypoint.sh:/entrypoint.sh
      - /snapraid/storage_c1/docker/seaweedfs/asagi_master_data:/data
    command: "master -ip=seaweed-master -volumeSizeLimitMB=200000"
  seaweed-filer:
    container_name: seaweed-filer
    image: chrislusf/seaweedfs:2.07_large_disk # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="seaweed-master:9333"'
    tty: true
    stdin_open: true
    volumes:
      - /snapraid/storage_c1/docker/seaweedfs/asagi_filer_data:/data
    depends_on:
      - seaweed-master
      - seaweed-volume-asagi-hdd-1
  seaweed-s3:
    image: chrislusf/seaweedfs:2.07_large_disk # use a remote image
    container_name: seaweed-s3
    ports:
      - 8333:8333
    command: 's3 -filer="seaweed-filer:8888" -config=/config.json'
    volumes:
      - /snapraid/storage_c1/docker/seaweedfs/config/config.json:/config.json:ro
    depends_on:
      - seaweed-master
      - seaweed-volume-asagi-hdd-1
      - seaweed-filer
  seaweed-volume-asagi-hdd-1:
    container_name: seaweed-volume-asagi-hdd-1
    image: chrislusf/seaweedfs:2.07_large_disk # use a remote image
    volumes:
      - /snapraid/storage_d25/seaweedfs/asagi-hdd-1:/data
    ports:
      - 18080:18080
    command: 'volume -mserver="seaweed-master:9333" -port=8080 -dataCenter=asagi -rack=hdd'
    depends_on:
      - seaweed-master
```
</details>

- `weed mount -filer=localhost:8888 -dir=/mnt/weed -collection=asagi-images -cacheDir=/snapraid/storage_c2/test/seaweed-cache -cacheCapacityMB=0 -chunkSizeLimitMB=2`
- Debian 9 (stretch)
- version 8000GB 2.07 4492122 linux amd64
- `filer.toml` is not used

**Expected behavior**
If the Volume Server is set to dynamically calculate the number of volumes at the start. It should check free space when creating a new volume and update the max number of volumes possible.

**Additional context**
The pronblem seems that the number of volumes is static, which might also cause a problem when the space on the disk is used up by something else.
In this case I freed up space, but the volumer server never recalculated the number of volumes possible.
Now there is also another question. What happens if the disk space is being used up by something else?

If on 2.5TB it reports 13 voluimes and I then use up 0.5TB of space, would that change the number of max volumes?
If not, that is a problem.
