### ISSUE TITLE
[s3] if there are no files, then the folders do not disappear

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1637]
**Describe the bug**
if there are no files, then the folders do not disappear

**System Setup**
```2.11```

**Expected behavior**
if there are no files, then the folders will also disappear

**Additional context**
This cause registry to work incorrectly
api request https://{{ registry }}/v2/{{ image }}/tags/list. returns deleted tags as there are empty folders on the seaweed(s3)
https://stackoverflow.com/questions/45207198/empty-folders-in-aws-s3

local-registry-compose.yml:
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs:local
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master -volumeSizeLimitMB=1024"
  volume:
    image: chrislusf/seaweedfs:local
    ports:
      - 8080:8080
      - 18080:18080
    command: "volume -mserver=master:9333 -port=8080 -ip=volume -max=0 -preStopSeconds=1"
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:local
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333"'
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:local
    ports:
      - 8333:8333
    command: '-v 9 s3 -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    command: 'minio server /data'
    environment:
      MINIO_ACCESS_KEY: "some_access_key1"
      MINIO_SECRET_KEY: "some_secret_key1"
    depends_on:
      - master
  registry1:
    image: registry:2
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5001" # seaweedfs s3
      REGISTRY_LOG_LEVEL: "debug"
      REGISTRY_STORAGE: "s3"
      REGISTRY_STORAGE_S3_REGION: "us-east-1"
      REGISTRY_STORAGE_S3_REGIONENDPOINT: "http://s3:8333"
      REGISTRY_STORAGE_S3_BUCKET: "registry"
      REGISTRY_STORAGE_S3_ACCESSKEY: "some_access_key1"
      REGISTRY_STORAGE_S3_SECRETKEY: "some_secret_key1"
      REGISTRY_STORAGE_S3_V4AUTH: "true"
      REGISTRY_STORAGE_S3_SECURE: "false"
      REGISTRY_STORAGE_S3_SKIPVERIFY: "true"
      REGISTRY_STORAGE_S3_ROOTDIRECTORY: "/"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_REDIRECT_DISABLE: "true"
      REGISTRY_VALIDATION_DISABLED: "true"
    ports:
      - 5001:5001
    depends_on:
      - s3
      - minio
  registry2:
    image: registry:2
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5002" # minio
      REGISTRY_LOG_LEVEL: "debug"
      REGISTRY_STORAGE: "s3"
      REGISTRY_STORAGE_S3_REGION: "us-east-1"
      REGISTRY_STORAGE_S3_REGIONENDPOINT: "http://minio:9000"
      REGISTRY_STORAGE_S3_BUCKET: "registry"
      REGISTRY_STORAGE_S3_ACCESSKEY: "some_access_key1"
      REGISTRY_STORAGE_S3_SECRETKEY: "some_secret_key1"
      REGISTRY_STORAGE_S3_V4AUTH: "true"
      REGISTRY_STORAGE_S3_SECURE: "false"
      REGISTRY_STORAGE_S3_SKIPVERIFY: "true"
      REGISTRY_STORAGE_S3_ROOTDIRECTORY: "/"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_REDIRECT_DISABLE: "true"
      REGISTRY_VALIDATION_DISABLED: "true"
    ports:
      - 5002:5002
    depends_on:
      - s3
      - minio
```

1.  ```docker-compose -f local-registry-compose.yml -p seaweedfs up```
2. 
``` 
aws --profile local --endpoint http://127.0.0.1:9000 s3 cp /tmp/root-dir s3://test/ --recursive 
upload: ../../../../tmp/root-dir/sub-dir/dir/empty-file to s3://test/sub-dir/dir/empty-file
aws --profile local --endpoint http://127.0.0.1:8333 s3 cp /tmp/root-dir s3://test/ --recursive 
upload: ../../../../tmp/root-dir/sub-dir/dir/empty-file to s3://test/sub-dir/dir/empty-file
```
2.
```
aws --profile local --endpoint http://127.0.0.1:9000 s3 rm s3://test/sub-dir/dir/empty-file
delete: s3://test/sub-dir/dir/empty-file
aws --profile local --endpoint http://127.0.0.1:8333 s3 rm s3://test/sub-dir/dir/empty-file
delete: s3://test/sub-dir/dir/empty-file
```
3. 

**Minio empty list**

```
aws --profile local --endpoint http://127.0.0.1:9000 s3 ls s3://test/
```

**Seaweed empty sub-dir on list**

```
aws --profile local --endpoint http://127.0.0.1:8333 s3 ls s3://test/
                           PRE sub-dir/
```
