### ISSUE TITLE
[weed mount]  write file error

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#1639]
**Describe the bug**
after weed mount, write file to filesystem,  get error（filer‘s log）:
```
{"log":"I1126 07:51:25     1 filer_grpc_server_sub_meta.go:175] + listener mount@172.25.0.1:33492\n","stream":"stderr","time":"2020-11-26T07:51:25.871024505Z"}
{"log":"I1126 07:51:25     1 filer_grpc_server_sub_meta.go:26]  mount@172.25.0.1:33492 starts to subscribe /registry01 from 2020-11-26 07:51:25.870030127 +0000 UTC\n","stream":"stderr","time":"2020-11-26T07:51:25.871089771Z"}
{"log":"I1126 07:55:00     1 filer_grpc_server_sub_meta.go:166] =\u003e client mount@172.25.0.1:33260: rpc error: code = Unavailable desc = transport is closing\n","stream":"stderr","time":"2020-11-26T07:55:00.619963419Z"}
{"log":"E1126 07:55:00     1 filer_grpc_server_sub_meta.go:49] processed to 2020-11-26 07:55:00.619624123 +0000 UTC: rpc error: code = Unavailable desc = transport is closing\n","stream":"stderr","time":"2020-11-26T07:55:00.62006021Z"}
{"log":"E1126 07:55:00     1 filer_delete_entry.go:79] deleting a folder /registry01/docker/registry/v2/repositories/nginx/_uploads/a22c3818-57f5-4e04-bac4-107e0a0a999c has children: hashstates ...\n","stream":"stderr","time":"2020-11-26T07:55:00.822087471Z"}
{"log":"I1126 07:55:00     1 filer_delete_entry.go:36] delete directory /registry01/docker/registry/v2/repositories/nginx/_uploads/a22c3818-57f5-4e04-bac4-107e0a0a999c: fail to delete non-empty folder: /registry01/docker/registry/v2/repositories/nginx/_uploads/a22c3818-57f5-4e04-bac4-107e0a0a999c\n","stream":"stderr","time":"2020-11-26T07:55:00.822130551Z"}
{"log":"E1126 07:55:00     1 filer_delete_entry.go:79] deleting a folder /registry01/docker/registry/v2/repositories/nginx/_uploads/a22c3818-57f5-4e04-bac4-107e0a0a999c has children: hashstates ...\n","stream":"stderr","time":"2020-11-26T07:55:00.822707754Z"}
```
The error in the last line above appears many many times

**System Setup**
version 2.12
seaweedfs-compose.yml:
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs:2.12
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs:2.12
    ports:
      - 8080:8080
      - 18080:18080
    command: "volume -mserver=master:9333 -port=8080 -ip=volume -publicUrl=localhost:8080 -max=0"
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:2.12
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333"'
    depends_on:
      - master
      - volume
```
docker-registry-config.yml:
```
version: 0.1
log:
  level: debug
storage:
  delete:
    enabled: true
  redirect:
    disable: true
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
validation:
  disabled: true
http:
  addr: 0.0.0.0:5001
```
run:
```
# set up seaweed
docker-compose -f seaweedfs-compose.yml -p seaweedfs up

# download source and build , get binary weed， omit...

# use weed mount to host path
sudo mkdir -p /mnt/registry
sudo ./weed mount -outsideContainerClusterMode -cacheCapacityMB=0 -filer=127.0.0.1:8888 -filer.path=/registry -dir=/mnt/registry

# setup docker registry
docker run -d -p 5001:5001 --name localregistry -v /home/orion/docker-registry-config.yml:/etc/docker/registry/config.yml -v /mnt/registry:/var/lib/registry registry:2
```
**Expected behavior**
write file success to filesystem from ```weed mount```

**Additional context**
1、```docker pull nginx:latest```
2、```docke tag nginx:latest 127.0.0.1:5001/nginx:latest```
3、```docker push 127.0.0.1:5001/nginx:latest```
```
The push refers to repository [127.0.0.1:5001/nginx]
7e914612e366: Pushing [==================================================>]  3.584kB
f790aed835ee: Pushing [==================================================>]  4.096kB
850c2400ea4d: Pushing [==================================================>]  3.072kB
7ccabd267c9f: Pushing [===========================>                       ]  35.35MB/63.65MB
f5600c6330da: Pushing [===============>                                   ]  21.67MB/69.24MB
```
The upload process is stuck，can not finish push

This error just likes https://github.com/chrislusf/seaweedfs/issues/1609, but this time docker registry backend use filesystem from ```weed mount```
