### ISSUE TITLE
Error while dialing dial tcp ip:19333: i/o timeout

### ISSUE THREAD

**Issue by yhan219** [chrislusf/seaweedfs#1783]
**Describe the bug**
I installed it using docker-compose. I have been using port 9333, so yesterday I closed port 19333 on the firewall, and now the same error appears like #1256. As you know, the port is not safe to open to the external network. How can I close 19333 on the external network and change the ip of the gprc to the ip of the internal network?

**System Setup**
- install it using docker-compose
- centos7
- version: weedfs 1.81

docker-compose.yml:
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
    volumes:
      - '/mnt/file/data:/data'
  volume:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    ports:
      - 9222:8080
      - 19222:18080
    command: 'volume -mserver="master:9333" -port=8080 -publicUrl=/file'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:1.81 # use a remote image
    ports:
      - 9255:8888
      - 19255:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
    volumes:
      - '/mnt/file/filerdb:/data/filerdb'
```

**Additional context**
my external ip:14.215.177.39
my internal ip:192.168.10.105
my error log:
```
I0205 07:27:08     1 common.go:51] response method:POST URL:/submit?ttl=10d&collection=work with httpStatus:500 and JSON:{"error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 14.215.177.39:19333: i/o timeout\""}
```
How can I make it access 192.168.10.105 instead of 14.215.177.39?
