### ISSUE TITLE
"mountpoint is not empty", but it is empty

### ISSUE THREAD

**Issue by Derkades** [chrislusf/seaweedfs#1819]
docker-compose
```yaml
  mount:
    image: chrislusf/seaweedfs
    volumes:
      - type: bind
        source: /mnt/weed
        target: /data
        bind:
          propagation: shared
    cap_add: ['sys_admin']
    devices: ['/dev/fuse:/dev/fuse']
    security_opt: ['apparmor:unconfined']
    depends_on: ['filer']
    # entrypoint: ls -a /data
    command: mount -filer=10.131.1.1:8888 -dir=/data -filer.path=/
    network_mode: service:tinc
```
produces
```
mount_1    | This is SeaweedFS version 30GB 2.26 ca74f64 linux amd64
mount_1    | mount point owner uid=0 gid=0 mode=drwxr-xr-x
mount_1    | current uid=0 gid=0
mount_1    | I0218 21:12:17     1 leveldb_store.go:40] filer store dir: /tmp/76f972a5/meta
mount_1    | I0218 21:12:17     1 file_util.go:23] Folder /tmp/76f972a5/meta Permission: -rwxr-xr-x
mount_1    | 2021/02/18 21:12:17 mount helper error: fusermount: mountpoint is not empty
mount_1    | 2021/02/18 21:12:17 mount helper error: fusermount: if you are sure this is safe, use the 'nonempty' mount option
mount_1    | I0218 21:12:17     1 mount_std.go:204] mount: fusermount: exit status 1
weed_mount_1 exited with code 0
```
but uncommenting `entrypoint` shows
```
mount_1    | .
mount_1    | ..
weed_mount_1 exited with code 0
```
so it is empty.

Setting it to a directory that doesn't exist (for example `/data/test`) shows the standard help message (like `weed help mount` would.

A similar docker setup worked for moosefs:
```yaml
  client:
    image: moosefs/client
    volumes:
      - type: bind
        source: /mnt/moose
        target: /mnt/moosefs
        bind:
          propagation: shared
    cap_add: ['sys_admin']
    devices: ['/dev/fuse:/dev/fuse']
    security_opt: ['apparmor:unconfined']
    depends_on: ['master']
    network_mode: service:tinc
```

**Comment by chrislusf** [comment]
Please share the full docker compose file.

**Comment by Derkades** [comment]
Tinc is a site-to-site vpn, connecting this stack (10.131.1.1) to others (10.131.2.1, etc.). I release running it over WAN this way is probably not seaweedfs's intended use case but it should work. This setup worked with MooseFS, but MooseFS was too slow to be used in this way due to how it works internally.
```yaml
  tinc:
    image: derkades/dsn_tinc
    ports:
     - 26488:26488
     - 9333:9333 # master web UI
     - 8888:8888 # filer web UI
     - 7333:7333 # webdav
     - 8899:8080 # volume1 web UI
    volumes:
      - type: bind
        source: ./tinc
        target: /etc/tinc/site2site
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      SITENAME: (removed)
      PORT: (removed)
      PUBADDR: (removed)
      DSN_LOCATION_ID: 1
    cap_add: ['net_admin']
    devices: ['/dev/net/tun:/dev/net/tun']

  master: # 9333, 19333
    image: chrislusf/seaweedfs
    network_mode: service:tinc
    volumes:
      - type: bind
        source: ./master
        target: /data
    command: 'master ip=10.131.1.1 -defaultReplication=100 -mdir=/data -volumeSizeLimitMB=1000'

  volume1:
    image: chrislusf/seaweedfs
    network_mode: service:tinc
    depends_on: [master]
    volumes:
      - type: bind
        source: /mnt/storj4/weed
        target: /data
    command: 'volume -mserver="10.131.1.1:9333" -ip="10.131.1.1" -port=8080 -dir=/data -dataCenter=robin -rack=server -max=20 -compactionMBps=1 -minFreeSpacePercent=10'

  filer: # 8888, 18888
    image: chrislusf/seaweedfs
    network_mode: service:tinc
    depends_on: [master]
    volumes:
      - type: bind
        source: ./filer
        target: /data
    command: 'filer -master="10.131.1.1:9333" -ip=10.131.1.1 -dataCenter=robin -defaultStoreDir=/data'

  # webdav:
  #   image: chrislusf/seaweedfs
  #   network_mode: service:tinc
  #   depends_on: [master]
  #   command: 'webdav -filer="10.131.1.1:8888"'

  mount:
    image: chrislusf/seaweedfs
    volumes:
      - type: bind
        source: /mnt/weed
        target: /data
        bind:
          propagation: shared
    cap_add: ['sys_admin']
    devices: ['/dev/fuse:/dev/fuse']
    security_opt: ['apparmor:unconfined']
    depends_on: ['filer']
    # entrypoint: ls -a /data
    command: mount -filer=10.131.1.1:8888 -dir=/data -filer.path=/
    network_mode: service:tinc
```

**Comment by chrislusf** [comment]
ok. Seems I could not run it locally.

**Comment by chrislusf** [comment]
can you try `weed mount -dirAutoCreate ...`

**Comment by Derkades** [comment]
Same output with `mount -filer=10.131.1.1:8888 -dirAutoCreate -dir=/data -filer.path=/`:
```
mount_1    | This is SeaweedFS version 30GB 2.23 318a3d2 linux amd64
mount_1    | mount point owner uid=0 gid=0 mode=drwxr-xr-x
mount_1    | current uid=0 gid=0
mount_1    | I0219 12:18:56     1 leveldb_store.go:40] filer store dir: /tmp/5f2dd572/meta
mount_1    | I0219 12:18:56     1 file_util.go:23] Folder /tmp/5f2dd572/meta Permission: -rwxr-xr-x
mount_1    | 2021/02/19 12:18:56 mount helper error: fusermount: mountpoint is not empty
mount_1    | 2021/02/19 12:18:56 mount helper error: fusermount: if you are sure this is safe, use the 'nonempty' mount option
mount_1    | I0219 12:18:56     1 mount_std.go:200] mount: fusermount: exit status 1
weed_mount_1 exited with code 0
```

**Comment by chrislusf** [comment]
Try it on a non existent folder?

**Comment by Derkades** [comment]
I did (e.g. `-dir=/data/test`), that produces a generic help output like `weed help mount` would

**Comment by Derkades** [comment]
Have you ever tried a weed FUSE mount in a container? I could not find an example in this repo

**Comment by chrislusf** [comment]
this is one https://github.com/chrislusf/seaweedfs/blob/master/docker/compose/local-mount-compose.yml

**Comment by Derkades** [comment]
thanks, I'll do some experiments tomorrow

**Comment by Derkades** [comment]
Ah I see, for some reason the container image comes with an empty "filerdldb2" folder in /data, so I can't use /data. Any other directory is fine.

**Comment by Derkades** [comment]
Do you know of anything that might cause mount propagation to the host to not work? My compose now looks like this
```yaml
  mount:
    image: chrislusf/seaweedfs
    privileged: true
    devices: ['fuse']
    security_opt: ['apparmor=unconfined']
    volumes:
      - type: bind
        source: /mnt/weed
        target: /mount
        bind:
          propagation: shared
    entrypoint: 'weed -v=4 mount -filer=10.131.1.1:8888 -dir=/mount -filer.path=/ -volumeServerAccess=filerProxy'
    depends_on: [master, filer]
    network_mode: service:tinc
```

This config (with a different entrypoint and image of course) works fine for other applications like MooseFS and rclone (also written in go). (see also https://superuser.com/a/1374808 and https://stackoverflow.com/a/53632103)

A test file uploaded through the filer web interface is present in the container, so the mount works fine:
```
# docker-compose exec mount ls -la /mount
total 1
-rw-r--r--    1 root     root             0 Feb 20 21:51 test
```
but not on the host:
```
# ls -la /mnt/weed 
total 8
drwxr-xr-x 2 root root 4096 Feb 20 22:50 .
drwxr-xr-x 8 root root 4096 Feb 18 21:56 ..
```

Nothing odd in syslog:
```
Feb 21 17:10:23 server systemd[1]: session-37542.scope: Succeeded.
Feb 21 17:10:32 server systemd[1]: run-docker-runtime\x2drunc-moby-479c03d32559254fc4941c02fee6f570531d0cb145505e6b6c1f2e051ca50d4b-runc.YkjFRR.mount: Succeeded.
Feb 21 17:11:00 server systemd[1]: Started Session 37544 of user root.
Feb 21 17:11:05 server systemd[1]: var-lib-docker-overlay2-7cca405eb9beacafb298c756dd7b2a3d60eeb63321cb0d0f4389bd7d59a45451-merged.mount: Succeeded.
Feb 21 17:11:05 server systemd[1257833]: var-lib-docker-overlay2-7cca405eb9beacafb298c756dd7b2a3d60eeb63321cb0d0f4389bd7d59a45451-merged.mount: Succeeded.
Feb 21 17:11:06 server containerd[2790]: time="2021-02-21T17:11:06.015479020+01:00" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/7253c6b07eb82e3f9f8975ccc836068511bb822fa81f7fc1768e17796c803cfe/shim.sock" debug=false pid=3443071
```

**Comment by chrislusf** [comment]
I can not tell...

**Comment by chrislusf** [comment]
can't tell. this may be useful
https://stackoverflow.com/questions/53631567/share-a-fuse-fs-mounted-inside-a-docker-container-through-volumes

**Comment by Derkades** [comment]
yes, that's one of the answers I used and it worked for all FUSE mount applications I used in the past, but weed mount seems to behave differently.

**Comment by chrislusf** [comment]
I am having issue similar to https://github.com/Mumie-hub/docker-services/issues/52

```
  mount_1:
    image: chrislusf/seaweedfs:local
    volumes:
      - type: bind
        source: /Users/chris/tmp/swmount
        target: /t1
        bind:
          propagation: shared
    privileged: true
    devices: ['fuse']
    security_opt: ['apparmor=unconfined']
    entrypoint: '/bin/sh -c "mkdir -p /t1 && weed -v=4 mount -filer=filer:8888 -dir=/t1 -filer.path=/ -volumeServerAccess=filerProxy"'
    depends_on:
      - master
      - volume
      - filer
```

docker compose Output:
```
...
Recreating seaweedfs_master_1 ... done
Recreating seaweedfs_volume_1 ... done
Recreating seaweedfs_filer_1  ... done
Recreating dd1394bf8d40_seaweedfs_mount_1_1 ... error

ERROR: for dd1394bf8d40_seaweedfs_mount_1_1  Cannot start service mount_1: path /host_mnt/Users/chris/tmp/swmount is mounted on /host_mnt but it is not a shared mount

ERROR: for mount_1  Cannot start service mount_1: path /host_mnt/Users/chris/tmp/swmount is mounted on /host_mnt but it is not a shared mount
ERROR: Encountered errors while bringing up the project.
make: *** [dev_mount] Error 1
```
