### ISSUE TITLE
Max volumes set to 8, but created volumes is 0

### ISSUE THREAD

**Issue by johncadengo** [chrislusf/seaweedfs#1880]
Using the stock docker-compose.yml file, but with a small change to the docker volume:

```
volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080  -metricsPort=9325'
    depends_on:
      - master
    volumes:
      - ./volume/data:/data
```

I added a `./volume/data:/data` volume, so it can persist locally. I set the permissions to that folder to writeable,

```
I0309 21:51:46     1 file_util.go:23] Folder /data Permission: -rwxrwxrwx
```

When I try to upload a file to filer, I get this error:

```
I0309 21:55:45     1 common.go:53] response method:POST URL:/ with httpStatus:500 and JSON:{"error":"rpc error: code = Unknown desc = No free volumes left!"}
```

When I check my volumes, it looks like this:

```
{
  "Version": "30GB 2.26 ca74f64",
  "Volumes": {
    "Free": 8,
    "Max": 8
  }
}
```

How do I get the volumes to be created?
