### ISSUE TITLE
Unexpected answer on API_ListParts method

### ISSUE THREAD

**Issue by Foxcool** [chrislusf/seaweedfs#1914]
I am trying to use the tusd library which should work with S3 and seaweedfs.
When I try to make multipart upload on seaweedfs, I got runtime nil pointer error.

In the ticket to the library, I described it in as much detail as I could. (https://github.com/tus/tusd/issues/464)

**Describe the bug**
Most likely the problem is that s3 adapter's response does not implement the S3 protocol correctly.

From the AWS S3 documentation it sounds like NextPartNumberMarker should be set if IsTruncated is true (https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html#AmazonS3-ListParts-response-NextPartNumberMarker):

    NextPartNumberMarker
    When a list is truncated, this element specifies the last part in the list, as well as the value to use for the part-number-marker request parameter in a subsequent request.

**System Setup**

docker-compose
```
version: '3.8'

services:

  master1:
    image: chrislusf/seaweedfs:2.31
    restart: always
    command: 'master -defaultReplication 000 -port 9333'
    ports:
      - 9333:9333

  filer:
    image: chrislusf/seaweedfs:2.31
    restart: always
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master master1:9333'
    tty: true
    stdin_open: true
    depends_on:
      - master1
      - volume1

  volume1:
    image: chrislusf/seaweedfs:2.31
    restart: always
    command: 'volume -dataCenter netrack -port 11001 -port.public 11001 -mserver master1:9333'
    ports:
      - 11001:11001
    depends_on:
      - master1

  s3:
    image: chrislusf/seaweedfs:2.31
    restart: always
    ports:
      - 8333:8333
    command: 's3 -filer filer:8888 -config /tmp/s3.json'
    volumes:
      - ./spec/s3.json:/tmp/s3.json:ro
    depends_on:
      - master1
      - volume1
      - filer

```
s3.json
```
{
  "identities": [
    {
      "name": "anonymous",
      "actions": [
        "Admin",
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    },
    {
      "name": "some_admin_user",
      "credentials": [
        {
          "accessKey": "some_access_key1",
          "secretKey": "some_secret_key1"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    }
  ]
}
```

**Expected behavior**
S3 API_ListParts:
When a list is truncated, NextPartNumberMarker must not be NIL.

**Screenshots**
![image](https://user-images.githubusercontent.com/323923/111420426-43a99580-86fc-11eb-8bd2-1f3fad2f7623.png)

**Additional context**
In the ticket to the library, I described it in as much detail as I could. (https://github.com/tus/tusd/issues/464)
