### ISSUE TITLE
Recover files from (.idx, .vif) when lose filer db.

### ISSUE THREAD

**Issue by fixNoobi** [chrislusf/seaweedfs#1965]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

**System Setup**
```
version: '3'

services:
  master:
    image: chrislusf/seaweedfs:2.24_large_disk # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master -mdir=/data-master"
    volumes:
      - /mnt/swfs/data-master/:/data-master/
  volume:
    image: chrislusf/seaweedfs:2.24_large_disk # use a remote image
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080  -metricsPort=9325 --dir=/data'
    volumes:
      - /mnt/swfs/data/:/data/
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:2.24_large_disk # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    volumes:
      - /mnt/swfs/filerldb2/:/data/filerldb2/
    stdin_open: true
    depends_on:
      - master
      - volume
  cronjob:
    image: chrislusf/seaweedfs:2.24_large_disk # use a remote image
    command: 'cronjob'
    environment:
      # Run re-replication every 2 minutes
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: master:9333 # Default: localhost:9333
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:2.24_large_disk # use a remote image
    ports:
      - 80:8333
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -metricsPort=9327 -config=/etc/seaweedfs/s3-credentials.json'
    depends_on:
      - master
      - volume
      - filer

```
- CentOS 7
- 2.24_large_disk

**Expected behavior**
When i add mount, filer data is losses.  
```    volumes:
      - /mnt/swfs/filerldb2/:/data/filerldb2/
```

**Additional context**
Question: May i can start reindex, for recovery files ( form .idx, .vif), and instert to new filer?
