### ISSUE TITLE
Filer not starting with Docker Swarm

### ISSUE THREAD

**Issue by victorberland** [chrislusf/seaweedfs#1992]
I'm setting up Seaweedfs for the first time in my Docker Swarm cluster, but running into issues with Filer. Everything related to volumes and master works perfectly, but I can't connect to Filer for some reason.

I spun up a cloud server at Scaleway to see if something was wrong with my cluster, but still the same issue. All it does i give me "could not connect" in the browser, but Docker still says it's running normally and logs only contain "filer store etcd".

I've generated a default filer config which gets mounted to /etc/seaweedfs. I also didn't have any luck removing this mount point and letting the container generate it itself.

Tried looking through the wiki to see if I maybe was missing some parameters, but didn't find anything. So maybe someone here could give a quick glance and see?

```
version: '3.8'

services:

  etcd:
    image: gasparekatapy/etcd
    networks:
      - net
    deploy:
      mode: global



  master:
    image: chrislusf/seaweedfs
    environment:
      WEED_MASTER_FILER_DEFAULT: "filer:8888"
      WEED_MASTER_SEQUENCER_TYPE: "raft"
    ports:
      - "9333:9333"
      - "19333:19333"
    networks:
      - net
    volumes:
      - ./:/etc/seaweedfs
    command:
      - 'master'
      - '-resumeState=true'
      - '-ip=master'
      - '-port=9333'
    deploy:
      mode: global



  filer:
    image: chrislusf/seaweedfs
    environment:
      WEED_LEVELDB2_ENABLED: "false"
      WEED_ETCD_ENABLED: "true"
      WEED_ETCD_SERVERS: "etcd:2379"
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
      - target: 18888
        published: 18888
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - ./:/etc/seaweedfs
    command:
      - 'filer'
      - '-ip=filer'
      - '-port=8888'
      - '-port.readonly=28888'
      - '-master=master:9333'
      - '-disableDirListing=true'
    deploy:
      mode: global



  volume1:
    image: chrislusf/seaweedfs
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - /data/1/:/data
      - ./:/etc/seaweedfs
    command:
      - 'volume'
      - '-mserver=master:9333'
      - '-max=0'
      - '-disk=ssd'
      - '-dataCenter=1'
      - '-ip=volume1'
      - '-port=8080'
    deploy:
      mode: global


networks:
  net:
  
  ```
