### ISSUE TITLE
no free volumes left !!!!!

### ISSUE THREAD

**Issue by homayoonsadeghiarkami** [chrislusf/seaweedfs#2010]
Hi 
Im deploying seaweedfs using docker-compose on one host for testing purposes. I try to run 3 volume server with one filer which use mysql2 with mysql container and one master. everything looks cool but when I try to upload a file I get the error like this:
`{"error":"rpc error: code = Unknown desc = no free volumes left for {\"replication\":{},\"ttl\":{\"Count\":0,\"Unit\":0},\"prealloacte\":1073741824}"}`
the docker-compose file is like 
```
version: '3.7'

services:
  master:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: seaweedfs:local
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
    volumes:
      - "seaweedfs_master_data:/data"
  volume1:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: seaweedfs:local
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -port=8080 -ip=volume1 -publicUrl=localhost:8080 -preStopSeconds=1 -disk=hdd1'
    depends_on:
      - master
    volumes:
      - "seaweedfs_volume1_data:/data"
  volume2:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: seaweedfs:local
    ports:
      - 8082:8082
      - 18082:18082
    command: 'volume -mserver="master:9333" -port=8082 -ip=volume2 -publicUrl=localhost:8082 -preStopSeconds=1 -disk=hdd1'
    depends_on:
      - master
    volumes:
      - "seaweedfs_volume2_data:/data"
  volume3:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: seaweedfs:local
    ports:
      - 8083:8083
      - 18083:18083
    command: 'volume -mserver="master:9333" -port=8083 -ip=volume3 -publicUrl=localhost:8083 -preStopSeconds=1 -disk=hdd1'
    depends_on:
      - master
    volumes:
      - "seaweedfs_volume3_data:/data"
  filer:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: seaweedfs:local
    ports:
      - 8888:8888
      - 18888:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume1
      - volume2
      - volume3
  mysql:
    restart: unless-stopped
    image: mysql 
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
    volumes:
      - "database_volume:/var/lib/mysql"
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "/home/mysql/mysql-files:/var/lib/mysql-files/"
      - "./mysql/scripts/seaweedfs.sql:/docker-entrypoint-initdb.d/init.sql"
    depends_on:
      - master
      - volume1
      - volume2
      - volume3
      - filer
  s3:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: s3:local
    ports:
      - 8333:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
      - master
      - volume1
      - volume2
      - volume3
      - filer
      - mysql

volumes: 
  seaweedfs_master_data:
    name: seaweedfs_master_data
    external: false
  seaweedfs_volume1_data:
    name: seaweedfs_volume1_data
    external: false
  seaweedfs_volume2_data:
    name: seaweedfs_volume2_data
    external: false
  seaweedfs_volume3_data:
    name: seaweedfs_volume3_data
    external: false
  database_volume:
    name: database_volume
    external: false
```
the filer.toml file is like
```
[mysql2]
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS `%s` (
    dirhash BIGINT,
    name VARCHAR(1000) BINARY,
    directory TEXT,
    meta LONGBLOB,
    PRIMARY KEY (dirhash, name)
  ) DEFAULT CHARSET=utf8;
"""
hostname = "mysql"
port = 3306
username = "seaweedfs"
password = "******"
database = "seaweedfs"
connection_max_idle = 2
connection_max_open = 100
connection_max_lifetime_seconds = 0
interpolateParams = false
# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO `%s` (dirhash,name,directory,meta) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE meta = VALUES(meta)"""
```
it will be great to help me everything seems okay to me but why?
