### ISSUE TITLE
Running on public internet

### ISSUE THREAD

**Issue by tobiasmuehl** [chrislusf/seaweedfs#2020]
Looking into running seaweedfs from servers that are directly exposed on the public internet, although not recommended.

Do not need to run Filer or S3 API, which makes things simpler. From my understanding, volume servers can be secured by JWT, but master servers can not. So I was thinking to block the master server port in the firewall and use a reverse proxy like nginx for the master servers and implement auth there. Would such a setup be reasonably secure?

Disabling HTTP and relying fully on gRPC looks possible but annoying as most clients use the HTTP API.

**Comment by chrislusf** [comment]
Sounds good. 

There is also connections between volume servers and master for some managerial operations. The proxy needs to allow this.
master <=== grpc ===> volume servers

**Comment by tobiasmuehl** [comment]
For master <> volume communication I was planning on using mutual TLS as described in the [wiki](https://github.com/chrislusf/seaweedfs/wiki/Security-Configuration). I will add some documentation of the proxy, probably nginx, haproxy, or caddy

**Comment by tobiasmuehl** [comment]
Setup is complete, initial testing was okay, perhaps you can give it a quick read and tell me if it looks correct. It can be turned into another wiki page as a step by step deployment guide.

----


# How to setup SeaweedFS on servers that face the public internet

This guide is for setting up master and volume servers only, we will *not* setup filer or S3. All services will run in Docker, which also acts as a firewall to block direct access to the HTTP API of the master server (single master, no HA). gRPC communication between volume and master server is encrypted with mutual TLS, all gRPC ports are exposed to the public internet. Master server HTTP API port (9333) is exposed via reverse proxy [Caddy](https://caddyserver.com/), which handles SSL termination and checks for an `Authorization` header (this header is completely separate from SeaweedFS JWT mechanism).

## Step by step setup

We will use 2 servers. Server 1 will host master, 2x volumes (2 disks, one volume server each), caddy reverse proxy. Server 2 will host 2 volume servers.

1. Install docker and docker-compose
2. Start master server. Using my own Dockerfile here to run the large_disk version and also because I got a bit confused by the provided `entrypoint.sh` overriding CLI arguments
  `Dockerfile`
  ```dockerfile
# todo: set version as ARG
# todo: use 2 step build process, copy over weed binary to fresh container (do not need curl and tar at runtime)
FROM alpine
RUN apk update && apk add wget tar
RUN wget https://github.com/chrislusf/seaweedfs/releases/download/2.40/linux_amd64_large_disk.tar.gz
RUN tar -xf linux_amd64_large_disk.tar.gz
RUN chmod +x weed
RUN mv weed /usr/bin/
  ```

`docker-compose.yml`

```yml
version: '3.7'
services:
        master:
                build: .
                volumes:
                        - /data/seaweedfs/master:/data/seaweedfs/master
                ports:
                        - 19333:19333
                entrypoint: weed master -mdir='/data/seaweedfs/master' -ip=<public ip of server> -volumeSizeLimitMB=100000 -defaultReplication=010
```

3. `docker-compose up` and see if it looks ok
4. Run volume server on server 2 (to test connection between physical servers)
  - same dockerfile
  - `docker-compose.yml`
```yml
version: '3.7'
services:
        volume-sda:
                build: .
                volumes:
                        - /data/seaweedfs/volume:/data/seaweedfs/volume
                ports:
                        - 8080:8080
                        - 18080:18080
                command: weed volume -mserver=<public IP of server 1>:9333 -dir=/data/seaweedfs/volume -ip=<public ip of this server (server2)>
```

5. `docker-compose up` on both servers and check that the master sees the volume
6. Follow [security guide](https://github.com/chrislusf/seaweedfs/wiki/Security-Configuration) to add secrets and certs. Scaffold `security.toml` file and generate certs, in this example, all certs are in `certs/` folder. Update `docker-compose.yml` of master server:
```yml
version: '3.7'
services:
        master:
                build: .
                volumes:
                        - /data/seaweedfs/master:/data/seaweedfs/master
                        - ./security.toml:/etc/seaweedfs/security.toml
                        - ./certs:/etc/seaweedfs/certs
                ports:
                        - 19333:19333
                entrypoint: weed master -mdir='/data/seaweedfs/master' -ip=<public ip of server> -volumeSizeLimitMB=100000 -defaultReplication=010
```
7. `docker-compose up` the master and volume. Because the volume server doesn't have the security config, the heartbeat should fail.
8. Copy `security.toml` and `certs/` folder to server2 and add mounts in `docker-compose.yml` file of volume server.
9. `docker-compose up`, now heartbeat should work and master should see volume server again
10. Test that JWT auth works as you expect. For that, edit docker-compose.yml of master server to temporarily expose port 9333 to the host machine. All testing will be done from command line of server 1:
  - `curl -i http://localhost:9333/dir/assign` should include bearer token
  - uploading with bearer token should work (for hand testing, might want to update the 10 second JWT timeout to something longer)
  - uploading without bearer token fails (3 test cases: not provided, incorrect provided, or token expired)
  - downloading with bearer token works
  - downloading without bearer token fails
  - delete with bearer token works, doesn't work without token
11. Great, JWT auth works as expected. `docker-compose down`, remove port `9333` from master server `docker-compose.yml`, clean data directory `rm -rf /data/seaweedfs/master/*` and `rm -rf /data/seaweedfs/volume/*`
12. Add caddyserver to master server `docker-compose.yml`. Caddy will automatically and without config issue a SSL cert from Lets Encrypt, redirect traffic from HTTP to HTTPS (on HTTP the header value can be sniffed, please remember to use HTTPS), and we will add config to check for `Authorization` header. A domain is needed for SSL. On master servers `docker-compose.yml`, add a new service:
```yml
        caddy:
                image: caddy:2.3.0-alpine
                volumes:
                        - ./Caddyfile:/etc/caddy/Caddyfile
                ports:
                        - 80:80
                        - 443:443
```

Add `Caddyfile`

```
seaweedfs.yourdomain.com

@bearertoken header Authorization "Bearer <your token>"
@notBearertoken not header Authorization "Bearer <your token>"

reverse_proxy @bearertoken master:9333

respond @notBearertoken 401
```

13. `docker-compose up`, wait for Caddy to get certs from LetsEncrypt, test it via curl:
   - `curl -i http://seaweedfs.yourdomain.com` redirects to `HTTPS`
   - `curl -i https://seaweedfs.yourdomain.com` responds with 401
   - `curl -H "Authorization: Bearer <your token>" https://seaweedfs.yourdomain.com/dir/assign` works
   - `curl -iH "Authorization: Bearer someOtherToken" https://seaweedfs.yourdomain.com/dir/assign` 401

14. Add more volume servers, take notice of port bindings. In my case, server 1 `docker-compose.yml` has master, volume-sda, volume-sdb, caddy, server 2 has volume-sda, volume-sdb.

`docker-compose.yml` server 2:

```yml
version: '3.7'
services:
        volume-sda:
                build: .
                volumes:
                        # /dev/sda4 mounts to /data
                        - /data/seaweedfs/volume:/data/seaweedfs/volume
                        - ./security.toml:/etc/seaweedfs/security.toml
                        - ./certs:/etc/seaweedfs/certs
                ports:
                        - 8080:8080
                        - 18080:18080
                command: weed volume -mserver=<master server ip>:9333 -dir=/data/seaweedfs/volume -ip=<publicIp>

        volume-sdb:
                build: .
                volumes:
                        # /dev/sdb1 mounts to /data2
                        - /data2/seaweedfs/volume:/data/seaweedfs/volume
                        - ./security.toml:/etc/seaweedfs/security.toml
                        - ./certs:/etc/seaweedfs/certs
                ports:
                        - 8081:8081
                        - 18081:18081
                command: weed volume -mserver=<master server ip>:9333 -dir=/data/seaweedfs/volume -ip=<publicIp>  -port=8081
```

## High availability

I haven't tested this, but this is how I would go about making it HA:
- Run master server on 3 or 5 physical servers
- Run caddy as a sidecar on every server that runs a master
- Install caddy from own Dockerfile, adding [redis plugin](github.com/gamalan/caddy-tlsredis) for distributed SSL cert storage and distributed locks for SSL cert issuing
- Run redis in high-availability mode, for example by [following this docker swarm guide](https://medium.com/@emmano3h/redis-high-availability-with-docker-swarm-2142a4d80b49). Caddy redis plugin probably doesn't allow multiple IP addresses, so might have to add `haproxy` sidecar to every caddy sidecar as well to load balance to redis cluster.
- Update `command` of volume servers to add all master server IPs

Alternatively:
- Use another caddy plugin for distributed SSL certs, not redis
- Use a loadbalancer-as-a-service that does SSL termination from some cloud provider
- Disable HTTP API on master server and use clients that can speak gRPC protocol

**Comment by Suika** [comment]
```
  'master')
  	ARGS="-mdir=/data -volumePreallocate -volumeSizeLimitMB=1024"
  	shift
  	exec /usr/bin/weed master $ARGS $@
	;;
```
short

`$@` == `master -mdir='/data/seaweedfs/master' -ip=<public ip of server> -volumeSizeLimitMB=100000 -defaultReplication=010`
`shift` strips firts part of the command, making `$@` ==  `-mdir='/data/seaweedfs/master' -ip=<public ip of server> -volumeSizeLimitMB=100000 -defaultReplication=010`
And everything together is:
`/usr/bin/weed master-mdir=/data -volumePreallocate -volumeSizeLimitMB=1024 -mdir='/data/seaweedfs/master' -ip=<public ip of server> -volumeSizeLimitMB=100000 -defaultReplication=010`

The arguments defined at the end overwrite the arguments at the beginning.

**Comment by tobiasmuehl** [comment]
Aaaaand it doesn't work. Uploading a file with replication 010 results in `failed to lookup for 9: Post \\\"http://xxxx:9333/dir/lookup\\\": dial tcp 144.76.202.89:9333: connect: connection refused\"`

@chrislusf Do volume servers communicate over HTTP with master when using replication?

**Comment by tobiasmuehl** [comment]
Aaaaand it doesn't work. Uploading a file with replication 010 results in `failed to lookup for 9: Post \\\"http://xxxx:9333/dir/lookup\\\": dial tcp xxxx:9333: connect: connection refused\"`

@chrislusf Do volume servers communicate over HTTP with master when using replication?

**Comment by tobiasmuehl** [comment]
Perhaps it's related to this line? How difficult is it to use gRPC instead? Alternatively can add more reverse proxies and use DNS and `/etc/hosts` to bridge the routing


https://github.com/chrislusf/seaweedfs/blob/c42b95c596f762dcca2bc9c7e7a918ab8ca8b206/weed/operation/lookup.go#L52

**Comment by ohayogirls** [comment]
What if I want to have a directory structure to show? I try to do something like your approach, use a web server to  proxies master  , implement auth and store the metadata(like filer) through the webserver.  
For example, If I want to upload a file, I need 

1. Request web server with "path" param
2. Web server would visit master's "/dir/assgin" API, and store the needed data in somewhere like redis.
3. Web server bring jwt, fid, volume url to response client.
4. Client use jwt upload file directly.

Is my approach available?(apologize for my poor English )

**Comment by tobiasmuehl** [comment]
@ohayogirls you will build your own service that maps paths and filenames to seaweedfs file ids to replace filer? I think that should work. Just see thread above, if you require replication, my setup will not work.

**Comment by chrislusf** [comment]
> Perhaps it's related to this line? How difficult is it to use gRPC instead? Alternatively can add more reverse proxies and use DNS and `/etc/hosts` to bridge the routing
> 
> https://github.com/chrislusf/seaweedfs/blob/c42b95c596f762dcca2bc9c7e7a918ab8ca8b206/weed/operation/lookup.go#L52

Need to change to gRPC. This issue has showed up before but needs some work.

**Comment by Suika** [comment]
This is a passing thought, but if (almost) everything is running on gRPC and there are problems with security setup between parts of seaweed cluster + http, why not have the `weed client` act as proxy for the requests?
i.e. API requests that are normally sent to parts of weed are sent to the client proxy, which in turn processes this data and turns it into grpc  request to be sent to whatever part of weed cluster it needs to.
But this sound like what Filer+S3 does.

**Comment by tobiasmuehl** [comment]
I added nginx as reverse proxy for gRPC. In short, here's config, still using docker compose:

**Server 1**
- Master
- Caddy
- Nginx
- Volume 1
- Volume 2

**Server 2**
- Volume 3
- Volume 4
- Nginx

Caddy checks HTTP header value and applies TLS, mentioned above. Now added nginx which reverse proxies both HTTP and gRPC to master (HTTP is proxied from nginx to caddy to master).

All seaweedfs docker `commands` need to be updated to use `nginx` as the master IP.

```diff
Server 1, master service
- command: weed master -mdir='/data/seaweedfs/master' -ip=<actual ipv4>
+ command: weed master -mdir='/data/seaweedfs/master' -ip=nginx

Volume servers on server 1 and 2
- command: weed volume -mserver=<actual ipv4>:9333
+ command: weed volume -mserver=nginx:9333
```

Nginx docker-compose:
```
        nginx:
                image: nginx:latest
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                        - ./certs/master01.crt:/etc/nginx/master01.crt
                        - ./certs/master01.key:/etc/nginx/master01.key
                        - ./certs/client01.crt:/etc/nginx/client01.crt
                        - ./certs/client01.key:/etc/nginx/client01.key
```

Nginx.conf. In short, 2 servers on ports 9333 (http) and 19333 (ssl http2) with proxy_pass and grpc_pass settings. SSL server needs present seaweedfs master certificate and use client certificate for the grpc reverse proxy

```
user                 nginx;
pid                  /var/run/nginx.pid;
worker_processes     auto;
worker_rlimit_nofile 65535;

# Load modules
include              /etc/nginx/modules-enabled/*.conf;

events {
    multi_accept       on;
    worker_connections 65535;
}

http {
    charset                utf-8;
    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            on;
    server_tokens          off;
    log_not_found          off;
    types_hash_max_size    2048;
    types_hash_bucket_size 64;
    client_max_body_size   16M;

    # MIME
    include                mime.types;
    default_type           application/octet-stream;

    # Logging
    access_log             /var/log/nginx/access.log;
    error_log              /var/log/nginx/error.log warn;

    # Connection header for WebSocket reverse proxy
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ""      close;
    }

    map $remote_addr $proxy_forwarded_elem {

        # IPv4 addresses can be sent as-is
        ~^[0-9.]+$        "for=$remote_addr";

        # IPv6 addresses need to be bracketed and quoted
        ~^[0-9A-Fa-f:.]+$ "for=\"[$remote_addr]\"";

        # Unix domain socket names cannot be represented in RFC 7239 syntax
        default           "for=unknown";
    }

    map $http_forwarded $proxy_add_forwarded {

        # If the incoming Forwarded header is syntactically valid, append to it
        "~^(,[ \\t]*)*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*([ \\t]*,([ \\t]*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*)?)*$" "$http_forwarded, $proxy_forwarded_elem";

        # Otherwise, replace it
        default "$proxy_forwarded_elem";
    }

    # Load configs

    server {
        listen      9333;
        listen      [::]:9333;
        server_name localhost;

        # security headers
        add_header X-XSS-Protection        "1; mode=block" always;
        add_header X-Content-Type-Options  "nosniff" always;
        add_header Referrer-Policy         "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
        add_header Permissions-Policy      "interest-cohort=()" always;

        # . files
        location ~ /\.(?!well-known) {
            deny all;
        }

        # reverse proxy
        location / {
            proxy_pass https://<domain of caddy>;

            proxy_set_header Authorization "Bearer <your token>";

            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;

            # Proxy headers
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        $connection_upgrade;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header Forwarded         $proxy_add_forwarded;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;

            # Proxy timeouts
            proxy_connect_timeout              60s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;
        }

    }

    server {
        listen      19333 ssl http2;
        listen      [::]:19333 ssl http2;
        server_name localhost;

        ssl_certificate     /etc/nginx/master01.crt;
        ssl_certificate_key /etc/nginx/master01.key;

        # security headers
        add_header X-XSS-Protection        "1; mode=block" always;
        add_header X-Content-Type-Options  "nosniff" always;
        add_header Referrer-Policy         "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
        add_header Permissions-Policy      "interest-cohort=()" always;

        # . files
        location ~ /\.(?!well-known) {
            deny all;
        }

        # reverse proxy
        location / {
            grpc_pass grpcs://<ipv4 of master>:19333;
            grpc_ssl_certificate     /etc/nginx/client01.crt;
            grpc_ssl_certificate_key /etc/nginx/client01.key;
        }
    }
}

```


One problem with this setup is that the log will be flooded with `master_1      | I0809 20:02:32     1 masterclient.go:120] master masterClient failed to receive from nginx:9333: rpc error: code = Internal desc = stream terminated by RST_STREAM with erro
r code: PROTOCOL_ERROR`, but everything still seems to work.
