### ISSUE TITLE
fuse mount cannot see files available via filer web access

### ISSUE THREAD

**Issue by michagruner** [chrislusf/seaweedfs#2060]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**
FUSE-mount cannot see files I see directly accessing the filer in a browser

**System Setup**
docker-compose.yml:
```
version: '2'

services:
  master0:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
    volumes:
      - /data/seaweedfs/master:/data
    command: "master -ip=weed1 -port=9333 -peers=weed1:9333 -mdir=/data/m1 -defaultReplication=010 -volumeSizeLimitMB=15000"
    restart: unless-stopped
  volume1:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
    volumes:
      - /data/seaweedfs/volume/data1:/data
    command: 'volume -mserver="weed1:9333" -port=8080 -ip=weed1 -dir=/data/ -publicUrl=weed1:8080 -dataCenter=myhome -rack=Proxmox max=0'
    restart: unless-stopped
    depends_on:
      - master0
  volume2:
    image: chrislusf/seaweedfs
    ports:
      - 8081:8081
      - 18081:18081
    volumes:
      - /data/seaweedfs/volume/data2:/data
    command: 'volume -mserver="weed1:9333" -port=8081 -ip=weed1 -dir=/data/ -publicUrl=weed1:8081 -dataCenter=myhome -rack=Proxmox max=0'
    restart: unless-stopped
    depends_on:
      - master0
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
    volumes:
      - /data/seaweedfs/filer:/data
      - ./filer.toml:/etc/seaweedfs/filer.toml
    command: 'filer -master="weed1:9333" -ip=weed1'
    restart: unless-stopped
    depends_on:
      - master0

```
filer.toml:

```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"

####################################################
# The following are filer store options
####################################################

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = false
dir = "./filerldb2"                                     # directory to store level db files

[leveldb3]
# similar to leveldb2.
# each bucket has its own meta store.
enabled = true
dir = "/data/filerldb3"                                 # directory to store level db files

##########################
##########################
# To add path-specific filer store:
#
# 1. Add a name following the store type separated by a dot ".". E.g., cassandra.tmp
# 2. Add a location configuraiton. E.g., location = "/tmp/"
# 3. Copy and customize all other configurations. 
#     Make sure they are not the same if using the same store type!
# 4. Set enabled to true
#
# The following is just using cassandra as an example
##########################
[redis2.tmp]
enabled = false
location = "/tmp/"
address  = "localhost:6379"
password = ""
database = 1
```

- OS version
`Linux data 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- output of `weed version`
`version 30GB 2.43 c48ef78 linux amd64`

**Expected behavior**
I see the same content on looking into the web-ui or on mounting via weed mount. What happens instead:

```
mgruner@data:~$ weed mount -filer=weed1:8888 -dir=/home/mgruner/weedfs/ -filer.path=/home/mgruner/ -allowOthers=false
This is SeaweedFS version 30GB 2.43 c48ef78 linux amd64
mount point owner uid=1001 gid=1002 mode=drwxr-xr-x
I0510 10:49:21  9866 leveldb_store.go:41] filer store dir: /tmp/d9cc6165/meta
I0510 10:49:21  9866 file_util.go:23] Folder /tmp/d9cc6165/meta Permission: -rwxr-xr-x
2021/05/10 10:49:21 mount helper error: fusermount: unsafe option suid ignored
I0510 10:49:21  9866 mount_std.go:221] mounted weed1:8888/home/mgruner to /home/mgruner/weedfs/

```
```
mgruner@data:~/weedfs/mgrunerY50$ ls -al
total 0

```

```
mgruner@data:~/weedfs/mgrunerY50$ curl -H "Accept: application/json" "http://weed1:8888/home/mgruner/mgrunerY50?pretty=y"
{
  "Path": "/home/mgruner/mgrunerY50",
  "Entries": [
    {
      "FullPath": "/home/mgruner/mgrunerY50/GRUNERFAMILYPC",
      "Mtime": "2021-05-09T08:37:35Z",
      "Crtime": "2021-05-09T08:37:35Z",
      "Mode": 2147484104,
      "Uid": 1001,
      "Gid": 1002,
      "Mime": "",
      "Replication": "010",
      "Collection": "",
      "TtlSec": 0,
      "DiskType": "",
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "Md5": null,
      "FileSize": 0,
      "Extended": null,
      "HardLinkId": null,
      "HardLinkCounter": 0,
      "Content": null
    },
    {
      "FullPath": "/home/mgruner/mgrunerY50/linux-mgruner",
      "Mtime": "2021-05-09T09:21:24Z",
      "Crtime": "2021-05-09T09:21:24Z",
      "Mode": 2147484141,
      "Uid": 1001,
      "Gid": 1002,
      "Mime": "",
      "Replication": "010",
      "Collection": "",
      "TtlSec": 0,
      "DiskType": "",
      "UserName": "",
      "GroupNames": null,
      "SymlinkTarget": "",
      "Md5": null,
      "FileSize": 164,
      "Extended": null,
      "HardLinkId": null,
      "HardLinkCounter": 0,
      "Content": null
    }
  ],
  "Limit": 100,
  "LastFileName": "linux-mgruner",
  "ShouldDisplayLoadMore": false

```
files were uploaded to filer via:

`weed filer.copy mgrunerY50/ http://weed1:8888/home/mgruner/`

**Screenshots**

**Additional context**
