### ISSUE TITLE
docker-registry with seaweedfs weed mount has error

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#2065]
**Describe the bug**
docker-registry with seaweedfs weed mount,  push image error

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
```
# setup master
weed master -port=9333 -mdir=/tmp/master0 -defaultReplication=000 -ip=localhost

# setup volume
weed volume -port=8080 -dir=/tmp/volume0 -ip=localhost -mserver=localhost:9333

# setup filer
weed filer -port=8888  -ip=localhost -master=localhost:9333

#weed mount
weed mount -filer=localhost:8888 -cacheCapacityMB=0 -cacheDir=/tmp/cache001 -dir=/root/mnt

#setup docker-registry
docker run -p 5001:5000 --rm \
    --name registry2 \
    -v /root/config.yml:/etc/docker/registry/config.yml -v /root/mnt/data:/data registry:2

#push image
root@qa-4:~# docker push 10.10.10.224:5001/ubuntu:16.04
The push refers to repository [10.10.10.224:5001/ubuntu]
1a1a19626b20: Pushing [==================================================>]  3.072kB
5b7dc8292d9b: Pushing  11.78kB
bbc674332e2e: Pushing [==================================================>]  15.87kB
da2785b7bb16: Pushing [>                                                  ]  525.3kB/130.7MB
unknown blob
```
- OS version
`Ubuntu 18.04.4 LTS`
- output of `weed version`
`version 30GB 2.41 8618526 linux amd64`
- if using filer, show the content of `filer.toml`
default

/root/config.yaml(without cache)
```
version: 0.1
log:
  fields:
    service: registry
storage:
        #  cache:
        # blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

**Expected behavior**
push & pull image successfully 

**Screenshots**
![image](https://user-images.githubusercontent.com/28077875/117948127-6abec500-b343-11eb-8a4e-c6a2e81281c0.png)

**Additional context**
master、volume、filer and  weed mount had no related warning and error log.

if use local filesystem, everything is fine.

if `/root/configy.yaml` enable cache:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
     blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
then, push image can be successful, but pull image will error(some small images pull many times will eventually succeed，but large images will not):

**pull big images**:
（btw, the test image can be pulled down from dockerhub(`docker pull jupyter/tensorflow-notebook:ubuntu-20.04`)

![image](https://user-images.githubusercontent.com/28077875/117952978-444f5880-b348-11eb-92f2-09cca527e42e.png)

![image](https://user-images.githubusercontent.com/28077875/117953890-0f8fd100-b349-11eb-846c-be53c01e471a.png)

At this time, if stop registry and restart it, then pull image is ok.
restart registry use same command:
```
docker run -p 5001:5000 --rm \
    --name registry2 \
    -v /root/config.yml:/etc/docker/registry/config.yml -v /root/mnt/data:/data registry:2
```

**pull small image**(pull many times, eventually succeed):
![image](https://user-images.githubusercontent.com/28077875/117951873-2c2b0980-b347-11eb-98f7-26cb4a7d8508.png)

BTW,  `version 30GB 2.28 37f104f linux amd64` version does not seem to have the above problem.

**Comment by paochiang** [comment]
If stop registry and restart it, then pull image is ok.
restart registry use same command:
```
docker run -p 5001:5000 --rm \
    --name registry2 \
    -v /root/config.yml:/etc/docker/registry/config.yml -v /root/mnt/data:/data registry:2
```

**Comment by chrislusf** [comment]
This ran fine on my Mac.  Not sure how to test this on Linux since I can only test it on a docker vm, and the registry example is on docker already.

**Comment by paochiang** [comment]
> If possible, could you please do some kind of binary search to find out which version may have caused this issue?

since version:` 2.40 release `: https://github.com/chrislusf/seaweedfs/releases/tag/2.40

**Comment by paochiang** [comment]
I think this issue may be related to: https://github.com/chrislusf/seaweedfs/issues/2068

**Comment by paochiang** [comment]
I try the latest version in https://github.com/chrislusf/seaweedfs/releases/tag/dev, push image still gets: `unkonwn blob`

**Comment by paochiang** [comment]
> This ran fine on my Mac with 2.47. Not sure how to test this on Linux since I can only test it on a docker vm, and the registry example is on docker already.

Is it possible to use a different external port to setup new registry?

**Comment by chrislusf** [comment]
Added another fix. https://github.com/chrislusf/seaweedfs/releases/tag/dev has the build ready.

**Comment by paochiang** [comment]
> Added another fix. https://github.com/chrislusf/seaweedfs/releases/tag/dev has the build ready.

Tried, it doesn't work.

**Comment by chrislusf** [comment]
what's your tried `weed version`?

**Comment by paochiang** [comment]
`version 30GB 2.47 26a55bbb5c1156ede00540c18d82a5c1f1713d7f linux amd64`

**Comment by chrislusf** [comment]
it's not the latest version.

**Comment by paochiang** [comment]
retried with version `version 30GB 2.47 e3f47ddb764b8618569c6b8f2e62b0a3caaaa3e8 linux amd64`, same error

**Comment by chrislusf** [comment]
ok. can not help now. Need a docker to run both `weed mount` and `registry`

**Comment by paochiang** [comment]
I rebuild a image(`paochiang/weedmount-registry:dev`, can be pulled down from dockerhub: https://registry.hub.docker.com/r/paochiang/weedmount-registry/tags?page=1&ordering=last_updated) thats can run both weed mount and registry,  could you use this image and below config reproduce the above problem with in docker container?

local-mount-compose.yml
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs:dev
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs:dev
    ports:
      - 7455:8080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080 -metricsPort=9325 -preStopSeconds=1 -publicUrl=localhost:7455'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:dev
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  mount_registry:
    image: paochiang/weedmount-registry:dev
    privileged: true
    ports:
      - "5001:5000"
    entrypoint: '/bin/sh /usr/start.sh'
    volumes:
      - /root/config.yaml:/etc/docker/registry/config.yml
    depends_on:
      - master
      - volume
      - filer
```

/root/config.yaml
```
version: 0.1
log:
  fields:
    service: registry
storage:
        #  cache:
        # blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
`rootdirectory` dir use `/var/lib/registry` because `weed mount` in image `paochiang/weedmount-registry:dev` target path is `/var/lib/registry`:
```
/usr/bin/weed mount -filer=filer:8888 -cacheCapacityMB=0 -cacheDir=/tmp/zAHmDrHitU -dir=/var/lib/registry -filer.path=/registry
```
weed version in image `paochiang/weedmount-registry:dev`: `version 30GB 2.47 e3f47ddb764b8618569c6b8f2e62b0a3caaaa3e8 linux amd64`


setup:
```
docker-compose -f /root/weedmount-registry/local-mount-compose.yml up
```

push image:
```
docker tag chrislusf/seaweedfs:2.23 127.0.0.1:5001/chrislusf/seaweedfs:2.23
docker push 127.0.0.1:5001/chrislusf/seaweedfs:2.23
```
then get error:
![image](https://user-images.githubusercontent.com/28077875/118111119-d6716280-b415-11eb-9df2-2e16408c6de7.png)

**Comment by chrislusf** [comment]
I can reproduce it. But to debug, I need to change the weed binary inside your docker image, and need to restart `weed mount` and `registry`.

**Comment by paochiang** [comment]
I created a repo: https://github.com/paochiang/weedmount-registry,  you can use this repo to build image: `paochiang/weedmount-registry` and can change weed binary by yourself.


To be able to restart `weed mount` and `registry` in container manually,  In Dockerfile, I set `ENTRYPOINT` to `sleep infinity `,  so after docker-compose up, we need to start the program manually.

./local-mount-compose.yml
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs:dev
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs:dev
    ports:
      - 7455:8080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080 -metricsPort=9325 -preStopSeconds=1 -publicUrl=localhost:7455'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:dev
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  mount_registry:
    image: paochiang/weedmount-registry:latest
    privileged: true
    ports:
      - "5001:5000"
    volumes:
      - ./config.yaml:/etc/docker/registry/config.yml
    depends_on:
      - master
      - volume
      - filer
```

set up
```
#docker-compose
docker-compose -f ./local-mount-compose.yml up

# start weed mount 
docker exec -it desktop_mount_registry_1 sh
mkdir /tmp/cache
/usr/bin/weed mount -filer=filer:8888 -cacheCapacityMB=0 -cacheDir=/tmp/cache -dir=/var/lib/registry -filer.path=/registry

#start registry  (in new terminal) 
docker exec -it desktop_mount_registry_1 sh
/entrypoint.sh /etc/docker/registry/config.ym
```

you can stop `weed mount` and `registry`  use `ctrl + c`, can also restart them with the command above.
