### ISSUE TITLE
Signed request requires setting up SeaweedFS S3 authentication

### ISSUE THREAD

**Issue by homayoonsadeghiarkami** [chrislusf/seaweedfs#2101]
Hi again I Setup minio-gateway-s3 for my s3 and I setup authentication for it by **config.json** but when I try to upload file I get the error `Signed request requires setting up SeaweedFS S3 authentication` in my log file and  `Failed to load resource: net::ERR_CONNECTION_RESET` in my console log, I didn`t have these problems before 2.49 release but now I got this error should I do something else?
```
{
    "identities": [
      {
        "name": "minio",
        "credentials": [
          {
            "accessKey": "eijuughu4eiD2",
            "secretKey": "sae2ooMeih9luipee9eep4emiHighoC9vohnozeid9dahju1yaedouK8teshahL5"
          }
        ],
        "actions": [
          "Admin",
          "Read",
          "List",
          "Tagging",
          "Write"
        ]
      }
    ]
  }
```

 ```
s3:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: seaweedfs:${TAG:-local}
    container_name: s3
    restart: unless-stopped
    command: 's3 -filer="filer:8888"'
    volumes: 
      - "./s3/config.json:/etc/seaweedfs/s3.json:ro"
      - "seaweedfs_s3_logs:/var/log/seaweedfs/s3"
    ports:
      - "8333:8333"
  minio-gateway-s3:
    image: minio/minio
    container_name: minio-gateway-s3
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: 'minio gateway s3 http://s3:8333'
    ports:
      - "9000:9000"
    depends_on:
      s3:
        condition: service_started
```
