### ISSUE TITLE
rpc error when upload file

### ISSUE THREAD

**Issue by hehejiuhuizhe** [chrislusf/seaweedfs#2320]
**Describe the bug**
I use docker swarm to test. When I upload file to filer, it fail due to rpc error. I can open the web page, but can't upload file.
![image](https://user-images.githubusercontent.com/29495241/132298460-77cb0de1-cc21-4872-bc77-787c28bdf3a2.png)
![image](https://user-images.githubusercontent.com/29495241/132298493-d0d31b2c-7a64-4119-8b57-d9c654af9c3c.png)
![image](https://user-images.githubusercontent.com/29495241/132298532-0e208a94-753b-42a5-9ef1-eb7d7a13638f.png)
![image](https://user-images.githubusercontent.com/29495241/132298574-443d5804-b1da-4db9-b700-d860f1526612.png)
![image](https://user-images.githubusercontent.com/29495241/132298621-f6c41bb2-d742-4ba3-b99d-a54bcb6c3a48.png)
And this is the error log:
![image](https://user-images.githubusercontent.com/29495241/132298687-a95cc638-7b5e-422c-9e5c-916525b5ae00.png)
![image](https://user-images.githubusercontent.com/29495241/132298738-a9ba22b4-d7b3-4d28-a94f-e68f3a72d266.png)

**System Setup**
This is my compose file, sea is a docker swarm network:
```yml
version: '3'
services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123345
      MONGO_INITDB_DATABASE: test
    ports:
      - 27020:27017
    networks:
      - sea  
    volumes: 
      - /home/ccw/test/test_weed/mongo:/data/db
      - /home/ccw/test/test_weed/mongo/mongodb.init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    deploy:
      restart_policy:
        condition: any  
  master:
    image: chrislusf/seaweedfs 
    ports:
      - 9333:9333
    networks:
      - sea 
    volumes: 
      - /home/ccw/test/test_weed/master:/master
    command: "master -ip=master -mdir=/master"
    deploy:
      restart_policy:
        condition: any  
  volume1:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
    networks:
      - sea 
    volumes: 
      - /home/ccw/test/test_weed/volume1:/volume1
    command: 'volume -mserver="master:9333" -port=8080 -dir=/volume1'
    deploy:
      restart_policy:
        condition: any  
  volume2:
    image: chrislusf/seaweedfs
    ports:
      - 8081:8080
    networks:
      - sea 
    volumes: 
      - /home/ccw/test/test_weed/volume2:/volume2
    command: 'volume -mserver="master:9333" -port=8080 -dir=/volume2'
    deploy:
      restart_policy:
        condition: any  
  filer1:
    image: chrislusf/seaweedfs 
    ports:
      - 8888:8888
    networks:
      - sea 
    volumes: 
      - /home/ccw/test/test_weed/filer.toml:/etc/seaweedfs/filer.toml
    command: 'filer -master="master:9333" '
    deploy:
      restart_policy:
        condition: any  
  filer2:
    image: chrislusf/seaweedfs 
    ports:
      - 8889:8888
    networks:
      - sea 
    volumes: 
      - /home/ccw/test/test_weed/filer.toml:/etc/seaweedfs/filer.toml
    command: 'filer -master="master:9333" '
    deploy:
      restart_policy:
        condition: any  
networks:
  sea:
    external: 
      name: sea
```

**Expected behavior**
Upload file successfully
