### ISSUE TITLE
S3 Configuration not persisting

### ISSUE THREAD

**Issue by clayscode** [chrislusf/seaweedfs#2443]
Currently on the latest version (2.77) having an issue getting the S3 configuration to persist between restarts. I'm running SeaweedFS on Docker and am starting the container like so:

```yaml
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -metricsPort=9327 -config=/seaweed/sw_config.json'
    depends_on:
      - master
      - volume
      - filer
    networks:
      - traefik-public
      - storage-net
      - 
    volumes:
      - /home/ubuntu/.seaweed:/seaweed
```

However, `sw_config.json` remains unchanged, and when I recreate the container, any dynamically creating configurations are wiped out.

My configuration file looks like so:
```json
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "exampleKey",
          "secretKey": "exampleSecret"
        }
      ],
      "actions": [
          "Admin"
      ]
    }
  ]
}
```

I'm not getting any errors from the S3 container, so am I doing something wrong here, or is this a bug? Thanks!

**Comment by clayscode** [comment]
It seems like none of the dynamic configuration is persisting even though I have `/etc/seaweedfs` mounted as a volume, `/data` mounted as a volume, as well as `-mdir` specified as a volume with the master container

**Comment by chrislusf** [comment]
Do not specify s3 config from CLI. Mixing the dynamic config and CLI is not supported.

**Comment by clayscode** [comment]
Ah, is this possible to add then? Use case is to dynamically add S3 keys and buckets. I guess a work around is to write to a file at the same time as when I dynamically add the keys, but automatically updating the config seems much better.

**Comment by chrislusf** [comment]
Just dynamically add the keys. The keys will be persisted in the filer store.

**Comment by clayscode** [comment]
I see. Apologies, I'm new to this project. It seems though that when I recreate the containers the configuration disappears. For instance 
```bash
ubuntu@dev:~$ sudo docker exec -it 66b30ba777ce weed shell -master=master:9333 -filer=filer:8888
>> fs.configure
{

}
>  fs.configure -locationPrefix=/buckets/ -volumeGrowthCount=1 -apply
{
  "locations": [
    {
      "locationPrefix": "/buckets/",
      "volumeGrowthCount": 1
    }
  ]
}
```

 but when I recreate the containers and re-check, it's empty
```bash
ubuntu@dev:~$ sudo docker exec -it 192ab962fbde weed shell -filer=filer:8888 -master=master:9333
>> 
>> fs.configure
{

}
```
This is the complete configuration I have 

```yaml
  master:
    image: chrislusf/seaweedfs # use a remote image
    command: "master -ip=master -volumePreallocate=false -volumeSizeLimitMB=512 -mdir=/seaweed"
    networks:
      - storage-net
    volumes:
      - "/home/ubuntu/.seaweed:/seaweed"
      - "/home/ubuntu/seaweed_data:/data"
      - 
  volume:
    image: chrislusf/seaweedfs # use a remote image
    command: 'volume -mserver="master:9333" -port=8080  -metricsPort=9325 -max=0'
    depends_on:
      - master
    networks:
      - storage-net

    volumes:
      - "/home/ubuntu/.seaweed:/etc/seaweedfs/"
      - "/home/ubuntu/seaweed_data:/data"

  filer:
    image: chrislusf/seaweedfs # use a remote image
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
    networks:
      - storage-net

    volumes:
      - "/home/ubuntu/.seaweed:/etc/seaweedfs/"
      - "/home/ubuntu/seaweed_data:/data"

  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -metricsPort=9327'
    depends_on:
      - master
      - volume
      - filer
    networks:
      - storage-net
    volumes:
      - /home/ubuntu/.seaweed:/seaweed
      - "/home/ubuntu/seaweed_data:/data"
```
