### ISSUE TITLE
registry use weed mount as backend storage has error

### ISSUE THREAD

**Issue by paochiang** [chrislusf/seaweedfs#2499]
**Describe the bug**
After I upgraded the Seaweedfs from `2.56` to `2.81`,  `weed mount` filesystem as registry backend storage cannot work.
**System Setup**
- output of `weed version`
version 30GB 2.81 5ea9715721fbad50a2b28bd5d3c65e13c0b57cb2 linux amd64

- reproduce

I build a image(`docker pull paochiang/weedmount-registry:latest`)  to run both weed mount and registry

./local-mount-compose.yml
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs:2.81
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs:2.81
    ports:
      - 7455:8080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080 -metricsPort=9325 -preStopSeconds=1 -publicUrl=localhost:7455'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:2.81
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  mount_registry:
    image: paochiang/weedmount-registry:latest
    privileged: true
    ports:
      - "5001:5000"
    #entrypoint: '/bin/sh /usr/start.sh'
    volumes:
      - ./config.yaml:/etc/docker/registry/config.yml
    depends_on:
      - master
      - volume
      - filer
```

./config.yaml
```
version: 0.1
log:
  fields:
    service: registry
storage:
        #  cache:
        # blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

set up
```
# seaweedfs setup
docker-compose -f ./local-mount-compose.yml up

# start weed mount 
docker exec -it 5e0b8547bed1 sh
weed mount -filer=filer:8888 -cacheCapacityMB=0 -cacheDir=/tmp/cache -dir=/var/lib/registry -filer.path=/registry

#start registry  (in new terminal) 
docker exec -it 5e0b8547bed1 sh
/entrypoint.sh /etc/docker/registry/config.yml
```

push images:
![image](https://user-images.githubusercontent.com/28077875/145344896-ab225ec3-b8e4-4909-938f-710e896d0248.png)

You can use this repo: https://github.com/paochiang/weedmount-registry to  change weed binary and build new image (execute build.sh file) 

**Expected behavior**
push image successfully

**Additional context**
Similar to ：https://github.com/chrislusf/seaweedfs/issues/2065
