### ISSUE TITLE
Download from s3 is interrupted if client downloads data at low speed

### ISSUE THREAD

**Issue by AlekseyFicht** [chrislusf/seaweedfs#2541]
Hello,

If filler and s3 are running on the same host, then the download of the file may be interrupted if the download speed of the client is very slow. (limit-rate 100K)

My Test via docker

I brought up the seaweed via docker-compose, I create a file and upload it, and ran curl for downloading, and it crashed again.

Server: SeaweedFS Filer 30GB 2.83

Error curl: (18) transfer closed with 396369981 bytes remaining to read

check.sh
```
#!/bin/bash

DOCKER_HOST="127.0.0.1"
FILER_URL="http://${DOCKER_HOST}:8888"
S3_URL="http://${DOCKER_HOST}:8333"
BUCKET=test
FILE_NAME=$(date "+%Y-%m-%d_%H-%M-%S").bin
DOWNLOAD_URL=${S3_URL}/${BUCKET}/${FILE_NAME}
ERRORS=errors.log

function prepareFile() {
	dd if=/dev/zero of=${FILE_NAME}  bs=100M count=1

	curl -v  \
	  -F "file=@${FILE_NAME}" \
	  "${FILER_URL}/buckets/${BUCKET}/"
	  
	rm "${FILE_NAME}"
}

function dl() {
    curl -v $DOWNLOAD_URL \
	    --limit-rate 100K \
		--http1.0 \
		--insecure \
	    --output /dev/null  \
		-H "Connection: close" \
		-w "%{time_total},%{size_download},%{speed_download}\n" \
		|| echo "Exit code for request $1 is $?" >> $ERRORS
}


echo "Failed requests:" > $ERRORS


prepareFile
dl 1 &
dl 2 &
dl 3 &
dl 4 &
dl 5 &
dl 6 &
dl 7 &
dl 8 &
dl 9 &
dl 10 &

wait
```

docker-compose.yml
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080  -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -metricsPort=9327'
    depends_on:
      - master
      - volume
      - filer
```

@chrislusf 
Please try to do similar steps on your own. Do you download a file using curl?

_Originally posted by @AlekseyFicht in https://github.com/chrislusf/seaweedfs/issues/2538#issuecomment-1002071323_
