### ISSUE TITLE
[raft] server.rv.deny.vote: cause stale term 

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#2833]
After restoring snapshots or load log

All master servers received a folder with metadata logs or snapshots with state.
But now the last index and last term are also updated
This leads to incorrect operation of the raft:
```
master1_1  | I0328 14:34:40     1 master_server.go:165] leader change event: master1:9334 => 
master1_1  | [raft]14:34:40.770336 [master1:9334 Term:305] server.deny.vote: cause out of date log:  master0:9333 Index :[ 147 ]  [ 46 ] Term :[ 304 ]  [ 5 ]
master1_1  | [raft]14:34:40.770449 [master1:9334 Term:305] server.loop.run  follower
master1_1  | [raft]14:34:40.770601 [master1:9334 Term:306] server.rv.vote:  master1:9334  votes for master2:9335 at term 306
master1_1  | [raft]14:34:40.771078 [master1:9334 Term:306] server.deny.vote: cause duplicate vote:  master0:9333  already vote for  master2:9335
master1_1  | [raft]14:34:40.771152 [master1:9334 Term:307] server.rv.vote:  master1:9334  votes for master2:9335 at term 307
master0_1  | [raft]14:34:40.771760 peer.vote.recv:  master0:9333 <- master1:9334
master0_1  | [raft]14:34:40.771835 [master0:9333 Term:306] server.candidate.vote: denied
master2_1  | [raft]14:34:40.772234 peer.vote.recv:  master2:9335 <- master1:9334
master2_1  | [raft]14:34:40.772362 [master2:9335 Term:307] server.candidate.vote.granted:  1
master2_1  | [raft]14:34:40.772407 [master2:9335 Term:307] server.candidate.recv.enough.votes
master2_1  | [raft]14:34:40.772582 [master2:9335 Term:307] server.loop.run  leader
master2_1  | [raft]14:34:40.772606 [master2:9335 Term:307] leaderLoop.set.PrevIndex to  147
master2_1  | I0328 14:34:40     1 master_server.go:165] leader change event:  => master2:9335
master2_1  | I0328 14:34:40     1 master_server.go:168] [ master2:9335 ] master2:9335 becomes leader.
master2_1  | [raft]14:34:40.773033 peer.heartbeat:  master0:9333 1.221923286s
master2_1  | [raft]14:34:40.773384 peer.heartbeat:  master1:9334 1.221923286s
master2_1  | [raft]14:34:40.773610 [master2:9335 Term:307] server.command.process
master2_1  | [raft]14:34:40.776047 peer.heartbeat.flush:  master1:9334
master2_1  | [raft]14:34:40.776092 log.entriesAfter.partial:  147   0x1aa6500
master2_1  | [raft]14:34:40.776112 log.entriesAfter: startIndex: 116  length 32
master2_1  | [raft]14:34:40.776128 peer.append.send: master2:9335->master1:9334 [prevLog:147 length: 1]
master2_1  | [raft]14:34:40.776166 peer.heartbeat.flush:  master0:9333
master2_1  | [raft]14:34:40.776188 log.entriesAfter.partial:  147   0x1aa6500
master2_1  | [raft]14:34:40.776208 log.entriesAfter: startIndex: 116  length 32
master2_1  | [raft]14:34:40.776250 peer.append.send: master2:9335->master0:9333 [prevLog:147 length: 1]
master1_1  | [raft]14:34:40.776793 log.truncate:  147
master1_1  | I0328 14:34:40     1 master_server.go:165] leader change event:  => ma
```

@chrislusf I still don't know what to do with it

can be played locally use PR https://github.com/chrislusf/seaweedfs/pull/2832:
local-cluster-compose.yml:
```
version: '2'

# s3cmd --no-ssl  --host=127.0.0.1:8333 mb s3://test3
services:
  master0:
    image: chrislusf/seaweedfs:local
    ports:
      - 9333:9333
      - 19333:19333
    command: "-v=4 master -mdir /data -volumeSizeLimitMB 100 -resumeState=true -heartbeatInterval=1000ms -electionTimeout=3s -ip=master0 -port=9333 -peers=master0:9333,master1:9334,master2:9335"
    volumes:
      - ./master/0:/data
    environment:
      WEED_MASTER_VOLUME_GROWTH_COPY_1: 1
      WEED_MASTER_VOLUME_GROWTH_COPY_2: 2
      WEED_MASTER_VOLUME_GROWTH_COPY_OTHER: 1
  master1:
    image: chrislusf/seaweedfs:local
    ports:
      - 9334:9334
      - 19334:19334
    command: "-v=4 master -mdir /data -volumeSizeLimitMB 100 -resumeState=true -heartbeatInterval=1000ms -electionTimeout=3s -ip=master1 -port=9334 -peers=master0:9333,master2:9335"
    volumes:
      - ./master/1:/data
    environment:
      WEED_MASTER_VOLUME_GROWTH_COPY_1: 1
      WEED_MASTER_VOLUME_GROWTH_COPY_2: 2
      WEED_MASTER_VOLUME_GROWTH_COPY_OTHER: 1
  master2:
    image: chrislusf/seaweedfs:local
    ports:
      - 9336:9335
      - 19336:19335
    command: "-v=4 master -mdir /data -volumeSizeLimitMB 100 -resumeState=true -heartbeatInterval=1000ms -electionTimeout=3s -ip=master2 -port=9335 -peers=master0:9333,master1:9334"
    volumes:
      - ./master/2:/data
    environment:
      WEED_MASTER_VOLUME_GROWTH_COPY_1: 1
      WEED_MASTER_VOLUME_GROWTH_COPY_2: 2
      WEED_MASTER_VOLUME_GROWTH_COPY_OTHER: 1
  volume1:
    image: chrislusf/seaweedfs:local
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -dataCenter=dc1 -rack=v1 -mserver="master0:9333,master1:9334,master3:9336" -port=8080 -ip=volume1 -publicUrl=localhost:8080 -preStopSeconds=1'
    depends_on:
      - master0
      - master1
  volume2:
    image: chrislusf/seaweedfs:local
    ports:
      - 8082:8082
      - 18082:18082
    command: 'volume -dataCenter=dc2 -rack=v2 -mserver="master0:9333,master1:9334,master3:9336" -port=8082 -ip=volume2 -publicUrl=localhost:8082 -preStopSeconds=1'
    depends_on:
      - master0
      - master1
  volume3:
    image: chrislusf/seaweedfs:local
    ports:
      - 8083:8083
      - 18083:18083
    command: 'volume -dataCenter=dc3 -rack=v3 -mserver="master0:9333,master1:9334,master3:9336" -port=8083 -ip=volume3 -publicUrl=localhost:8083 -preStopSeconds=1'
    depends_on:
      - master0
      - master1
  filer:
    image: chrislusf/seaweedfs:local
    ports:
      - 8888:8888
      - 18888:18888
      - 8111:8111
      - 8333:8333
    command: 'filer -defaultReplicaPlacement=100 -iam -master="master0:9333,master1:9334,master3:9335" -s3'
    depends_on:
      - master0
      - master1
      - volume1
      - volume2
```

1. make cluster 
2. Send TERM to all masters for make snapshots
```
docker kill -s TERM seaweedfs_master0_1
docker kill -s TERM seaweedfs_master1_1
docker kill -s TERM seaweedfs_master2_1
```
2. ctrl+C and make cluste
