### ISSUE TITLE
seaweedfs randomly loses files

### ISSUE THREAD

**Issue by coelho** [chrislusf/seaweedfs#3097]
Setup:

- Kubernetes on Ubuntu 22.04 (containerd)
- Version: 3.0.4
- 3x Master
- 3x Filer (storage: `mysql` [also tried `redis3_cluster`])
- 3x Volume (index: `leveldb`)
- FUSE Mount (via CSI) in a Pod (with 3x Filers)

Helm for seaweedfs:

```
global:
  enableReplication: true
  replicationPlacment: "001"

filer:
  replicas: 3
  dirListLimit: "100000000"
  extraEnvironmentVars:
    WEED_MYSQL_ENABLED: "true"
    WEED_MYSQL_HOSTNAME: "galera-active.default.svc.cluster.local"
    WEED_MYSQL_PORT: "3306"
    WEED_MYSQL_DATABASE: "seaweedfs"
    WEED_MYSQL_USERNAME: "seaweedfs"
    WEED_MYSQL_CONNECTION_MAX_IDLE: "5"
    WEED_MYSQL_CONNECTION_MAX_OPEN: "75"
  nodeSelector: |
    seaweedfs-filer: "true"

master:
  replicas: 3
  nodeSelector: |
    seaweedfs-master: "true"

volume:
  replicas: 3
  nodeSelector: |
    seaweedfs-volume: "true"
  compactionMBps: "1000"
  index: leveldb
```

Helm for seaweedfs-csi-driver:

```
imagePullPolicy: Always
seaweedfsFiler: 'seaweedfs-filer-0.seaweedfs-filer:8888,seaweedfs-filer-1.seaweedfs-filer:8888,seaweedfs-filer-2.seaweedfs-filer:8888'
storageClassName: seaweedfs
```

A directory listing with metadata in a large tree returns a seemingly random subset of files. Every time executed, it returns a different sub-set. Restarting Masters/Filers/Volumes has no effect.

This is more specifically a Docker Registry.
Example workload is: `registry garbage-collect -m /etc/docker/registry/config.yml -d` (dry run)

Executing this multiple times (in the same Pod) returns any random number of files to prune, even though the directory is not changing (no writes):

```
1002 blobs marked, 2146 blobs and 718 manifests eligible for deletion
...
996 blobs marked, 2152 blobs and 717 manifests eligible for deletion
...
1022 blobs marked, 2125 blobs and 718 manifests eligible for deletion
```

The issue also seems to get worse over time. More and more files are lost, even though there are no writes.
