### ISSUE TITLE
docker-compose DefaultDataCenter IP adress issue

### ISSUE THREAD

**Issue by simonbruneaud** [chrislusf/seaweedfs#396]
Hi, i'm trying to use docker-compose to run seaweedfs containers, but I can't access the volume default URL

**I used the sample docker-compose.yml**
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
    command: "master"
    networks:
      default:
        aliases:
          - seaweed_master
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
    command: 'volume -max=5 -mserver="master:9333" -port=8080'
    depends_on: 
     - master
    networks:
      default:
        aliases:
          - seaweed_volume
```

Then I have run the command `docker-compose  -f docker/docker-compose.yml up`

**Got 2 containers running:**
```
dc21c9c68658        chrislusf/seaweedfs   "/entrypoint.sh volum"   3 minutes ago       Up 3 minutes        0.0.0.0:8080->8080/tcp, 9333/tcp   docker_volume_1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
033d2e1cca42        chrislusf/seaweedfs   "/entrypoint.sh maste"   3 minutes ago       Up 6 seconds        8080/tcp, 0.0.0.0:9333->9333/tcp   docker_master_1
```

I can use POST request on the PORT 9333, but the URL provided to send the file is 172.18.0.2 and it looks like I can't access this IP.

**Is there a way to specify a IP for this volume.**
I tried this (in docker-compose.yml)
```
command: 'volume -dir="/tmp/bmpr" -max=5 -mserver="localhost:9333" -port=8080'
```

**Note: I'm using windows 10, and the docker default IP adress is 192.168.99.100 (not localhost)**
