### ISSUE TITLE
How can i set ip address in docker mode

### ISSUE THREAD

**Issue by okjesse** [chrislusf/seaweedfs#611]
i want to use ip address like 192.168.1.248 to save file,not localhost ,how can i fix this in docker mode.

**Comment by ZzMark** [comment]
i think mod to `hostname -i` in `/docker/entrypoint.sh` , build.

but i dont know how to mod

**Comment by trackleaf** [comment]
what I did to get around this is I created my own image using the Dockerfile but left out the entrypoint stuff....

```
FROM frolvlad/alpine-glibc:alpine-3.5
 
# Tried to use curl only (curl -o /tmp/linux_amd64.tar.gz ...), however it turned out that the following tar command failed with "gzip: stdin: not in gzip format"
RUN apk add --no-cache --virtual build-dependencies --update wget curl ca-certificates && \
    wget -P /tmp https://github.com/$(curl -s -L https://github.com/chrislusf/seaweedfs/releases/latest | egrep -o 'chrislusf/seaweedfs/releases/download/.*/linux_amd64.tar.gz') && \
    tar -C /usr/bin/ -xzvf /tmp/linux_amd64.tar.gz && \
    apk del build-dependencies && \
    rm -rf /tmp/*

EXPOSE 8080
EXPOSE 9333

VOLUME /data
```

then I used it in docker-compose.yml as follows

```
seaweed-master:
    image: '{your-new-image}'
    ports:
      - '9333:9333'
    command: "/usr/bin/weed master -mdir='/data' -ip='{external-ip-address-server-1}'"
    volumes:
      - /seaweedm:/data
    deploy:
      placement:
        constraints:
          - node.hostname == server-1
    networks:
      default:
        aliases:
          - seaweed_master
  seaweed-volume:
    image: '{your-new-image}'
    ports:
      - '8080:8080'
    command: "/usr/bin/weed volume -max=5 -mserver='seaweed-master:9333' -ip='{external-ip-address-server-2}' -port=8080"
    volumes:
      - /seaweedv:/data
    depends_on:
      - seaweed-master
    deploy:
      placement:
        constraints:
        - node.hostname == server-2
    networks:
      default:
        aliases:
          - seaweed_volume
```

I'm using this in a docker swarm....just testing it all out at the moment, nothing serious, but I created a constraint so the master seaweedfs will be on server-1 and the volumes will be on other specific servers in the swarms.

so far it's working on my three little virtualBox VMs with PHP uploading images to seaweedfs. The return json has the correct external ip address.
