### ISSUE TITLE
Cannot upload files when using docker-compose

### ISSUE THREAD

**Issue by fabianTMC** [chrislusf/seaweedfs#744]
**Describe the bug**
I am using node-seaweedfs to upload files to seaweed-fs that is running using docker-compose. 

**System Setup**
```yml
version: '3'
services:
    seaweedfs_master:
         container_name: "seaweedfs_master"
         image: "chrislusf/seaweedfs"
         command: master -mdir="/data" -defaultReplication=110
         ports:
             - "9333:9333"
    
    seaweedfs_volume1:
         container_name: "seaweedfs_volume1"
         image: "chrislusf/seaweedfs"
         command: volume -dir="/data" -mserver="seaweedfs_master:9333" -dataCenter=digital_ocean -rack=rack1 -ip seaweedfs_master
         volumes:
             - ~/seaweedfs-data:/data
         links:
            - seaweedfs_master
         ports:
             - "8080:8080"
```

The error I get is:
```
Cannot grow volume group! No matching data node found!
digital_ocean:Only has 1 racks, not enough for 2.
```

What am I doing wrong?
