### ISSUE TITLE
 heartbeat error [unknown port]

### ISSUE THREAD

**Issue by chengsu** [chrislusf/seaweedfs#785]
**Describe the bug**
Got  heartbeat error
> I1207 03:56:34     1 volume_grpc_client_to_master.go:32] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: address tcp/9333\": unknown port"

**System Setup**
I use docker-compose, 1 master and 1 volume on the same machine, here is my docker-compose.yml file:
```
#docker-compose.yml
weed-master:
    image: chrislusf/seaweedfs
    restart: always
    volumes:
    - /data/docker/weed-master:/data
    ports:
    - 9333:9333
    command: ['master','-mdir="/data"']

  weed-volume:
    image: chrislusf/seaweedfs
    restart: always
    ports:
    - 8081:8081
    - 18081:18081
    command: ['volume','-max=5000','-dir="/data"','-mserver="weed-master:9333"','-port=8081']
    volumes:
    - /data/docker/weed-slave:/data
    depends_on:
    - weed-master
```
