### ISSUE TITLE
use docker images!  ' -dir /data ' arg  is invalid

### ISSUE THREAD

**Issue by chenxushuo** [chrislusf/seaweedfs#993]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**

When i use seaweedfs with docker，and my container has tow network interface，‘-dir  ’ arg will be invalid .

**System Setup**

images:  chrislusf/seaweedfs:latest

**Expected behavior**

**Screenshots**
example:
docker-compose.yaml file like:
```
version: '2'
services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 9333:9333
    - 19333:19333
    command: "master"
    networks:
    - web
    - test
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 8080:8080
    - 18080:18080
    command: 'volume -max=15 -mserver="master:9333" -port=8080'
    volumes:
    - "./volume:/data"
    depends_on:
    - master
    networks:
    - web
    - test

networks:
  web:
  test:
```
after `up -d` , run cmd `ps -ef` will echo :
 ```
root     14683 14662  0 15:14 ?        00:00:00 /usr/bin/weed master -ip 192.168.80.2 192.168.96.2 -mdir /data
root     14927 14907  0 15:14 ?        00:00:00 /usr/bin/weed volume -max=15 -mserver=master:9333 -port=8080 -ip 192.168.96.3 192.168.80.3 -dir /data
```
'-ip ' arg will get tow var " 192.168.80.2 192.168.96.2 " ,and then,the args  after '-ip' will be invalid!!
